# varforge config: INDEL_ML2_VAF1318_0502 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf1318_0502
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF1318_0502
  read_length: 150
  coverage: 11328.1
  platform: illumina

fragment:
  model: normal
  mean: 236.1
  sd: 20.6

quality:
  mean_quality: 36
  tail_decay: 0.0032

tumour:
  purity: 0.263560
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 3.00
  family_size_sd: 1.51

chromosomes:
  - chr1

seed: 245380
