# varforge config: INDEL_ML2_VAF0320_0811 — VAF 3.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0320_0811
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0320_0811
  read_length: 150
  coverage: 2698.9
  platform: illumina

fragment:
  model: normal
  mean: 271.5
  sd: 48.3

quality:
  mean_quality: 36
  tail_decay: 0.0028

tumour:
  purity: 0.064075
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0300_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 8.53
  family_size_sd: 1.72

chromosomes:
  - chr1

seed: 265681
