# varforge config: INDEL_ML2_VAF0006_0808 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0006_0808
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0006_0808
  read_length: 150
  coverage: 6986.0
  platform: illumina

fragment:
  model: normal
  mean: 185.9
  sd: 42.9

quality:
  mean_quality: 33
  tail_decay: 0.0047

tumour:
  purity: 0.001278
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 4.24
  family_size_sd: 2.24

chromosomes:
  - chr1

seed: 265883
