# varforge config: INDEL_ML2_VAF0500_0231 — VAF 5.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0500_0231
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0500_0231
  read_length: 150
  coverage: 1751.6
  platform: illumina

fragment:
  model: normal
  mean: 226.8
  sd: 19.8

quality:
  mean_quality: 32
  tail_decay: 0.0018

tumour:
  purity: 0.100011
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0500_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 4.78
  family_size_sd: 2.39

chromosomes:
  - chr1

seed: 269096
