# varforge config: INDEL_ML2_VAF0023_0832 — VAF 0.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0023_0832
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0023_0832
  read_length: 150
  coverage: 3971.6
  platform: illumina

fragment:
  model: normal
  mean: 249.6
  sd: 33.3

quality:
  mean_quality: 34
  tail_decay: 0.0032

tumour:
  purity: 0.004585
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0025_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.62
  family_size_sd: 1.37

chromosomes:
  - chr1

seed: 258593
