# varforge config: INDEL_ML2_VAF0075_0786 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0075_0786
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0075_0786
  read_length: 150
  coverage: 3577.0
  platform: illumina

fragment:
  model: normal
  mean: 132.3
  sd: 31.6

quality:
  mean_quality: 35
  tail_decay: 0.0026

tumour:
  purity: 0.014918
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 3.13
  family_size_sd: 0.70

chromosomes:
  - chr1

seed: 223735
