# varforge config: INDEL_ML2_VAF0004_0521 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0004_0521
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0004_0521
  read_length: 150
  coverage: 913.6
  platform: illumina

fragment:
  model: normal
  mean: 200.2
  sd: 49.3

quality:
  mean_quality: 39
  tail_decay: 0.0030

tumour:
  purity: 0.000757
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 5.96
  family_size_sd: 3.07

chromosomes:
  - chr1

seed: 269166
