# varforge config: INDEL_ML2_VAF0179_0705 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0179_0705
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0179_0705
  read_length: 150
  coverage: 2049.4
  platform: illumina

fragment:
  model: normal
  mean: 212.4
  sd: 21.4

quality:
  mean_quality: 34
  tail_decay: 0.0015

tumour:
  purity: 0.035744
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0175_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 2.37
  family_size_sd: 0.57

chromosomes:
  - chr1

seed: 280781
