# varforge config: INDEL_ML2_VAF0029_0321 — VAF 0.3000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0029_0321
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0029_0321
  read_length: 150
  coverage: 9572.7
  platform: illumina

fragment:
  model: normal
  mean: 155.0
  sd: 20.6

quality:
  mean_quality: 37
  tail_decay: 0.0035

tumour:
  purity: 0.005714
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0030_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 2.32
  family_size_sd: 1.34

chromosomes:
  - chr1

seed: 299135
