# varforge config: INDEL_ML2_VAF0771_0844 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0771_0844
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0771_0844
  read_length: 150
  coverage: 19868.4
  platform: illumina

fragment:
  model: normal
  mean: 247.7
  sd: 46.5

quality:
  mean_quality: 34
  tail_decay: 0.0048

tumour:
  purity: 0.154258
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 5.32
  family_size_sd: 1.45

chromosomes:
  - chr1

seed: 241879
