# varforge config: INDEL_ML2_VAF0057_0559 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0057_0559
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0057_0559
  read_length: 150
  coverage: 4454.6
  platform: illumina

fragment:
  model: normal
  mean: 148.0
  sd: 43.4

quality:
  mean_quality: 38
  tail_decay: 0.0036

tumour:
  purity: 0.011374
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0060_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 4.29
  family_size_sd: 1.80

chromosomes:
  - chr1

seed: 214049
