# varforge config: INDEL_ML2_VAF0857_0865 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0857_0865
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0857_0865
  read_length: 150
  coverage: 3432.8
  platform: illumina

fragment:
  model: normal
  mean: 144.2
  sd: 18.7

quality:
  mean_quality: 31
  tail_decay: 0.0027

tumour:
  purity: 0.171332
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 5.91
  family_size_sd: 2.80

chromosomes:
  - chr1

seed: 215834
