# varforge config: INDEL_ML2_VAF1354_0398 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf1354_0398
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF1354_0398
  read_length: 150
  coverage: 1850.3
  platform: illumina

fragment:
  model: normal
  mean: 192.7
  sd: 20.9

quality:
  mean_quality: 39
  tail_decay: 0.0018

tumour:
  purity: 0.270882
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.83
  family_size_sd: 1.72

chromosomes:
  - chr1

seed: 290988
