# varforge config: INDEL_ML2_VAF0040_0558 — VAF 0.4000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0040_0558
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0040_0558
  read_length: 150
  coverage: 5473.4
  platform: illumina

fragment:
  model: normal
  mean: 142.8
  sd: 44.5

quality:
  mean_quality: 36
  tail_decay: 0.0032

tumour:
  purity: 0.007937
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0040_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 7.35
  family_size_sd: 4.32

chromosomes:
  - chr1

seed: 214239
