# varforge config: INDEL_ML2_VAF0080_0789 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0080_0789
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0080_0789
  read_length: 150
  coverage: 609.0
  platform: illumina

fragment:
  model: normal
  mean: 181.3
  sd: 30.1

quality:
  mean_quality: 37
  tail_decay: 0.0039

tumour:
  purity: 0.016042
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0075_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.32
  family_size_sd: 1.17

chromosomes:
  - chr1

seed: 255716
