# varforge config: INDEL_ML2_VAF0880_0545 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0880_0545
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0880_0545
  read_length: 150
  coverage: 15394.3
  platform: illumina

fragment:
  model: normal
  mean: 255.2
  sd: 22.8

quality:
  mean_quality: 33
  tail_decay: 0.0046

tumour:
  purity: 0.175911
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 4.76
  family_size_sd: 1.39

chromosomes:
  - chr1

seed: 203261
