# varforge config: INDEL_ML2_VAF0695_0081 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0695_0081
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0695_0081
  read_length: 150
  coverage: 860.9
  platform: illumina

fragment:
  model: normal
  mean: 158.1
  sd: 16.0

quality:
  mean_quality: 37
  tail_decay: 0.0028

tumour:
  purity: 0.138988
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0700_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 6.16
  family_size_sd: 1.83

chromosomes:
  - chr1

seed: 230501
