# varforge config: INDEL_ML2_VAF0011_0856 — VAF 0.1000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0011_0856
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0011_0856
  read_length: 150
  coverage: 654.2
  platform: illumina

fragment:
  model: normal
  mean: 157.5
  sd: 18.7

quality:
  mean_quality: 35
  tail_decay: 0.0017

tumour:
  purity: 0.002248
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 3.08
  family_size_sd: 0.93

chromosomes:
  - chr1

seed: 209727
