# varforge config: INDEL_ML2_VAF0581_0633 — VAF 6.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0581_0633
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0581_0633
  read_length: 150
  coverage: 2996.3
  platform: illumina

fragment:
  model: normal
  mean: 223.2
  sd: 49.4

quality:
  mean_quality: 38
  tail_decay: 0.0022

tumour:
  purity: 0.116237
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0600_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 3.36
  family_size_sd: 1.42

chromosomes:
  - chr1

seed: 239570
