# varforge config: INDEL_ML2_VAF0191_0580 — VAF 2.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0191_0580
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0191_0580
  read_length: 150
  coverage: 8183.0
  platform: illumina

fragment:
  model: normal
  mean: 268.3
  sd: 37.0

quality:
  mean_quality: 40
  tail_decay: 0.0010

tumour:
  purity: 0.038218
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0200_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 4.31
  family_size_sd: 1.92

chromosomes:
  - chr1

seed: 244143
