# varforge config: INDEL_ML2_VAF0685_0124 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0685_0124
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0685_0124
  read_length: 150
  coverage: 5023.6
  platform: illumina

fragment:
  model: normal
  mean: 174.7
  sd: 19.1

quality:
  mean_quality: 32
  tail_decay: 0.0034

tumour:
  purity: 0.137085
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0700_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 4.42
  family_size_sd: 1.11

chromosomes:
  - chr1

seed: 210878
