# varforge config: INDEL_ML2_VAF0005_0586 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0005_0586
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0005_0586
  read_length: 150
  coverage: 13482.6
  platform: illumina

fragment:
  model: normal
  mean: 250.8
  sd: 42.7

quality:
  mean_quality: 35
  tail_decay: 0.0035

tumour:
  purity: 0.001073
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 8.65
  family_size_sd: 3.85

chromosomes:
  - chr1

seed: 210415
