# varforge config: INDEL_ML2_VAF0118_0726 — VAF 1.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0118_0726
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0118_0726
  read_length: 150
  coverage: 11083.7
  platform: illumina

fragment:
  model: normal
  mean: 238.2
  sd: 44.4

quality:
  mean_quality: 31
  tail_decay: 0.0040

tumour:
  purity: 0.023677
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 5.67
  family_size_sd: 1.96

chromosomes:
  - chr1

seed: 242816
