# varforge config: INDEL_ML2_VAF0155_0315 — VAF 1.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0155_0315
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0155_0315
  read_length: 150
  coverage: 527.1
  platform: illumina

fragment:
  model: normal
  mean: 178.4
  sd: 35.0

quality:
  mean_quality: 35
  tail_decay: 0.0024

tumour:
  purity: 0.030974
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0150_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 7.32
  family_size_sd: 2.16

chromosomes:
  - chr1

seed: 225461
