# varforge config: INDEL_ML2_VAF0263_0195 — VAF 2.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0263_0195
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0263_0195
  read_length: 150
  coverage: 19688.5
  platform: illumina

fragment:
  model: normal
  mean: 222.3
  sd: 28.0

quality:
  mean_quality: 37
  tail_decay: 0.0016

tumour:
  purity: 0.052633
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0250_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 7.97
  family_size_sd: 2.46

chromosomes:
  - chr1

seed: 222325
