# varforge config: INDEL_ML2_VAF0231_0850 — VAF 2.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0231_0850
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0231_0850
  read_length: 150
  coverage: 3238.8
  platform: illumina

fragment:
  model: normal
  mean: 175.0
  sd: 36.5

quality:
  mean_quality: 31
  tail_decay: 0.0019

tumour:
  purity: 0.046132
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0250_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 6.35
  family_size_sd: 1.43

chromosomes:
  - chr1

seed: 275105
