# varforge config: INDEL_ML2_VAF0104_0243 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0104_0243
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0104_0243
  read_length: 150
  coverage: 9341.9
  platform: illumina

fragment:
  model: normal
  mean: 258.1
  sd: 23.5

quality:
  mean_quality: 38
  tail_decay: 0.0025

tumour:
  purity: 0.020844
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 9.90
  family_size_sd: 4.42

chromosomes:
  - chr1

seed: 206042
