# varforge config: INDEL_ML2_VAF0715_0456 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0715_0456
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0715_0456
  read_length: 150
  coverage: 10427.4
  platform: illumina

fragment:
  model: normal
  mean: 145.6
  sd: 15.1

quality:
  mean_quality: 39
  tail_decay: 0.0037

tumour:
  purity: 0.142954
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 9.82
  family_size_sd: 4.10

chromosomes:
  - chr1

seed: 245535
