# varforge config: INDEL_ML2_VAF0340_0265 — VAF 3.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0340_0265
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0340_0265
  read_length: 150
  coverage: 4480.0
  platform: illumina

fragment:
  model: normal
  mean: 262.0
  sd: 34.7

quality:
  mean_quality: 37
  tail_decay: 0.0022

tumour:
  purity: 0.068067
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0350_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 1.99
  family_size_sd: 0.63

chromosomes:
  - chr1

seed: 281091
