# varforge config: INDEL_ML2_VAF0042_0758 — VAF 0.4000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0042_0758
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0042_0758
  read_length: 150
  coverage: 4571.4
  platform: illumina

fragment:
  model: normal
  mean: 216.8
  sd: 50.0

quality:
  mean_quality: 39
  tail_decay: 0.0029

tumour:
  purity: 0.008339
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0040_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 8.33
  family_size_sd: 2.17

chromosomes:
  - chr1

seed: 212208
