# varforge config: INDEL_ML2_VAF0066_0339 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0066_0339
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0066_0339
  read_length: 150
  coverage: 1586.0
  platform: illumina

fragment:
  model: normal
  mean: 258.4
  sd: 32.0

quality:
  mean_quality: 33
  tail_decay: 0.0028

tumour:
  purity: 0.013184
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0060_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 2.14
  family_size_sd: 0.75

chromosomes:
  - chr1

seed: 296532
