# varforge config: INDEL_ML2_VAF0806_0033 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0806_0033
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0806_0033
  read_length: 150
  coverage: 5349.0
  platform: illumina

fragment:
  model: normal
  mean: 267.6
  sd: 47.3

quality:
  mean_quality: 38
  tail_decay: 0.0018

tumour:
  purity: 0.161275
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 3.62
  family_size_sd: 0.85

chromosomes:
  - chr1

seed: 236737
