# varforge config: INDEL_ML2_VAF0851_0853 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0851_0853
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0851_0853
  read_length: 150
  coverage: 16201.7
  platform: illumina

fragment:
  model: normal
  mean: 237.6
  sd: 31.7

quality:
  mean_quality: 30
  tail_decay: 0.0038

tumour:
  purity: 0.170241
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 4.24
  family_size_sd: 0.97

chromosomes:
  - chr1

seed: 240558
