# varforge config: INDEL_ML2_VAF0319_0322 — VAF 3.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0319_0322
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0319_0322
  read_length: 150
  coverage: 11217.3
  platform: illumina

fragment:
  model: normal
  mean: 193.6
  sd: 22.1

quality:
  mean_quality: 30
  tail_decay: 0.0049

tumour:
  purity: 0.063879
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0300_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.00
  family_size_sd: 1.15

chromosomes:
  - chr1

seed: 235256
