# varforge config: INDEL_ML2_VAF0016_0689 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0016_0689
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0016_0689
  read_length: 150
  coverage: 17243.6
  platform: illumina

fragment:
  model: normal
  mean: 250.4
  sd: 24.9

quality:
  mean_quality: 38
  tail_decay: 0.0013

tumour:
  purity: 0.003129
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 7.48
  family_size_sd: 3.58

chromosomes:
  - chr1

seed: 238530
