# varforge config: INDEL_ML2_VAF0902_0531 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0902_0531
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0902_0531
  read_length: 150
  coverage: 6114.4
  platform: illumina

fragment:
  model: normal
  mean: 136.1
  sd: 46.3

quality:
  mean_quality: 33
  tail_decay: 0.0012

tumour:
  purity: 0.180315
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 5.66
  family_size_sd: 2.64

chromosomes:
  - chr1

seed: 295128
