# varforge config: INDEL_ML2_VAF0775_0797 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0775_0797
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0775_0797
  read_length: 150
  coverage: 1337.7
  platform: illumina

fragment:
  model: normal
  mean: 131.8
  sd: 45.0

quality:
  mean_quality: 39
  tail_decay: 0.0042

tumour:
  purity: 0.155051
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 2.81
  family_size_sd: 0.82

chromosomes:
  - chr1

seed: 223746
