# varforge config: INDEL_ML2_VAF0003_0372 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0003_0372
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0003_0372
  read_length: 150
  coverage: 2262.2
  platform: illumina

fragment:
  model: normal
  mean: 252.5
  sd: 32.1

quality:
  mean_quality: 36
  tail_decay: 0.0035

tumour:
  purity: 0.000639
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 7.16
  family_size_sd: 2.51

chromosomes:
  - chr1

seed: 209046
