# varforge config: INDEL_ML2_VAF1165_0340 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf1165_0340
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF1165_0340
  read_length: 150
  coverage: 8093.9
  platform: illumina

fragment:
  model: normal
  mean: 176.6
  sd: 32.7

quality:
  mean_quality: 36
  tail_decay: 0.0022

tumour:
  purity: 0.232968
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.77
  family_size_sd: 0.68

chromosomes:
  - chr1

seed: 218880
