# varforge config: INDEL_ML2_VAF0836_0899 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0836_0899
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0836_0899
  read_length: 150
  coverage: 2469.3
  platform: illumina

fragment:
  model: normal
  mean: 227.6
  sd: 38.8

quality:
  mean_quality: 30
  tail_decay: 0.0030

tumour:
  purity: 0.167107
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 6.81
  family_size_sd: 2.07

chromosomes:
  - chr1

seed: 222277
