# varforge config: INDEL_ML2_VAF0012_0320 — VAF 0.1000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0012_0320
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0012_0320
  read_length: 150
  coverage: 11084.6
  platform: illumina

fragment:
  model: normal
  mean: 208.8
  sd: 42.3

quality:
  mean_quality: 36
  tail_decay: 0.0031

tumour:
  purity: 0.002382
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 1.55
  family_size_sd: 0.76

chromosomes:
  - chr1

seed: 202328
