# varforge config: INDEL_ML2_VAF0167_0882 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_indel_ml2_vaf0167_0882
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML2_VAF0167_0882
  read_length: 150
  coverage: 516.0
  platform: illumina

fragment:
  model: normal
  mean: 257.0
  sd: 28.5

quality:
  mean_quality: 34
  tail_decay: 0.0043

tumour:
  purity: 0.033496
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 3.07
  family_size_sd: 1.17

chromosomes:
  - chr1

seed: 232729
