# varforge config: INS_ML2_VAF1250_0189 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf1250_0189
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF1250_0189
  read_length: 150
  coverage: 4225.8
  platform: illumina

fragment:
  model: normal
  mean: 258.8
  sd: 20.0

quality:
  mean_quality: 37
  tail_decay: 0.0045

tumour:
  purity: 0.250050
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 3.32
  family_size_sd: 1.17

chromosomes:
  - chr1

seed: 298145
