# varforge config: INS_ML2_VAF0423_0372 — VAF 4.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0423_0372
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0423_0372
  read_length: 150
  coverage: 7621.7
  platform: illumina

fragment:
  model: normal
  mean: 152.5
  sd: 41.1

quality:
  mean_quality: 37
  tail_decay: 0.0024

tumour:
  purity: 0.084599
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0400_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 3.04
  family_size_sd: 1.04

chromosomes:
  - chr1

seed: 225308
