# varforge config: INS_ML2_VAF0349_0217 — VAF 3.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0349_0217
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0349_0217
  read_length: 150
  coverage: 5278.9
  platform: illumina

fragment:
  model: normal
  mean: 272.5
  sd: 42.8

quality:
  mean_quality: 35
  tail_decay: 0.0047

tumour:
  purity: 0.069869
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0350_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.29
  family_size_sd: 1.25

chromosomes:
  - chr1

seed: 265530
