# varforge config: INS_ML2_VAF0659_0326 — VAF 7.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0659_0326
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0659_0326
  read_length: 150
  coverage: 10764.6
  platform: illumina

fragment:
  model: normal
  mean: 252.8
  sd: 49.7

quality:
  mean_quality: 37
  tail_decay: 0.0026

tumour:
  purity: 0.131796
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 8.24
  family_size_sd: 4.63

chromosomes:
  - chr1

seed: 202788
