# varforge config: INS_ML2_VAF1280_0248 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf1280_0248
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF1280_0248
  read_length: 150
  coverage: 2477.4
  platform: illumina

fragment:
  model: normal
  mean: 212.4
  sd: 21.6

quality:
  mean_quality: 36
  tail_decay: 0.0048

tumour:
  purity: 0.256084
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 7.33
  family_size_sd: 2.58

chromosomes:
  - chr1

seed: 201934
