# varforge config: INS_ML2_VAF1028_0130 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf1028_0130
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF1028_0130
  read_length: 150
  coverage: 2999.4
  platform: illumina

fragment:
  model: normal
  mean: 187.3
  sd: 17.8

quality:
  mean_quality: 38
  tail_decay: 0.0014

tumour:
  purity: 0.205615
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 4.61
  family_size_sd: 1.30

chromosomes:
  - chr1

seed: 202315
