# varforge config: INS_ML2_VAF0033_0354 — VAF 0.3500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0033_0354
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0033_0354
  read_length: 150
  coverage: 6285.6
  platform: illumina

fragment:
  model: normal
  mean: 157.1
  sd: 24.9

quality:
  mean_quality: 32
  tail_decay: 0.0049

tumour:
  purity: 0.006539
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 5.27
  family_size_sd: 1.60

chromosomes:
  - chr1

seed: 298943
