# varforge config: INS_ML2_VAF0680_0261 — VAF 7.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0680_0261
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0680_0261
  read_length: 150
  coverage: 5839.2
  platform: illumina

fragment:
  model: normal
  mean: 241.2
  sd: 23.0

quality:
  mean_quality: 39
  tail_decay: 0.0024

tumour:
  purity: 0.135900
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0700_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 3.92
  family_size_sd: 2.02

chromosomes:
  - chr1

seed: 213640
