# varforge config: INS_ML2_VAF1134_0125 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf1134_0125
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF1134_0125
  read_length: 150
  coverage: 7342.8
  platform: illumina

fragment:
  model: normal
  mean: 135.7
  sd: 49.8

quality:
  mean_quality: 39
  tail_decay: 0.0014

tumour:
  purity: 0.226832
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 7.74
  family_size_sd: 3.08

chromosomes:
  - chr1

seed: 213021
