# varforge config: INS_ML2_VAF0012_0160 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0012_0160
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0012_0160
  read_length: 150
  coverage: 838.1
  platform: illumina

fragment:
  model: normal
  mean: 238.4
  sd: 36.6

quality:
  mean_quality: 32
  tail_decay: 0.0035

tumour:
  purity: 0.002354
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 1.56
  family_size_sd: 0.49

chromosomes:
  - chr1

seed: 283399
