# varforge config: INS_ML2_VAF0041_0302 — VAF 0.4000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0041_0302
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0041_0302
  read_length: 150
  coverage: 15721.0
  platform: illumina

fragment:
  model: normal
  mean: 180.8
  sd: 43.8

quality:
  mean_quality: 36
  tail_decay: 0.0028

tumour:
  purity: 0.008177
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0040_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 3.68
  family_size_sd: 1.64

chromosomes:
  - chr1

seed: 264672
