# varforge config: INS_ML2_VAF0059_0332 — VAF 0.6000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0059_0332
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0059_0332
  read_length: 150
  coverage: 2657.2
  platform: illumina

fragment:
  model: normal
  mean: 236.0
  sd: 49.1

quality:
  mean_quality: 37
  tail_decay: 0.0017

tumour:
  purity: 0.011718
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0060_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 1.94
  family_size_sd: 0.76

chromosomes:
  - chr1

seed: 232355
