# varforge config: INS_ML2_VAF0011_0348 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0011_0348
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0011_0348
  read_length: 150
  coverage: 1422.2
  platform: illumina

fragment:
  model: normal
  mean: 190.7
  sd: 16.6

quality:
  mean_quality: 35
  tail_decay: 0.0042

tumour:
  purity: 0.002206
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 4.69
  family_size_sd: 2.51

chromosomes:
  - chr1

seed: 223378
