# varforge config: INS_ML2_VAF0005_0136 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0005_0136
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0005_0136
  read_length: 150
  coverage: 12704.1
  platform: illumina

fragment:
  model: normal
  mean: 179.7
  sd: 29.4

quality:
  mean_quality: 37
  tail_decay: 0.0049

tumour:
  purity: 0.000963
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 2.35
  family_size_sd: 1.34

chromosomes:
  - chr1

seed: 221276
