# varforge config: INS_ML2_VAF0016_0104 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0016_0104
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0016_0104
  read_length: 150
  coverage: 2437.2
  platform: illumina

fragment:
  model: normal
  mean: 272.6
  sd: 23.7

quality:
  mean_quality: 38
  tail_decay: 0.0035

tumour:
  purity: 0.003166
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 6.17
  family_size_sd: 3.03

chromosomes:
  - chr1

seed: 212840
