# varforge config: INS_ML2_VAF0005_0098 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0005_0098
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0005_0098
  read_length: 150
  coverage: 731.4
  platform: illumina

fragment:
  model: normal
  mean: 132.9
  sd: 49.4

quality:
  mean_quality: 34
  tail_decay: 0.0046

tumour:
  purity: 0.000959
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.75
  family_size_sd: 1.20

chromosomes:
  - chr1

seed: 231078
