# varforge config: INS_ML2_VAF1431_0253 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf1431_0253
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF1431_0253
  read_length: 150
  coverage: 5289.4
  platform: illumina

fragment:
  model: normal
  mean: 218.4
  sd: 15.6

quality:
  mean_quality: 31
  tail_decay: 0.0045

tumour:
  purity: 0.286192
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 4.92
  family_size_sd: 2.25

chromosomes:
  - chr1

seed: 217951
