# varforge config: INS_ML2_VAF0003_0060 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0003_0060
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0003_0060
  read_length: 150
  coverage: 6385.9
  platform: illumina

fragment:
  model: normal
  mean: 244.9
  sd: 44.4

quality:
  mean_quality: 37
  tail_decay: 0.0045

tumour:
  purity: 0.000652
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 3.78
  family_size_sd: 1.11

chromosomes:
  - chr1

seed: 283511
