# varforge config: INS_ML2_VAF0006_0113 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0006_0113
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0006_0113
  read_length: 150
  coverage: 2293.8
  platform: illumina

fragment:
  model: normal
  mean: 200.6
  sd: 37.4

quality:
  mean_quality: 36
  tail_decay: 0.0040

tumour:
  purity: 0.001126
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 6.00
  family_size_sd: 1.55

chromosomes:
  - chr1

seed: 264524
