# varforge config: INS_ML2_VAF0027_0052 — VAF 0.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0027_0052
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0027_0052
  read_length: 150
  coverage: 3332.2
  platform: illumina

fragment:
  model: normal
  mean: 213.7
  sd: 25.6

quality:
  mean_quality: 35
  tail_decay: 0.0034

tumour:
  purity: 0.005373
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0025_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 1.70
  family_size_sd: 0.67

chromosomes:
  - chr1

seed: 234142
