# varforge config: INS_ML2_VAF0027_0299 — VAF 0.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf0027_0299
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF0027_0299
  read_length: 150
  coverage: 585.4
  platform: illumina

fragment:
  model: normal
  mean: 247.1
  sd: 48.8

quality:
  mean_quality: 39
  tail_decay: 0.0028

tumour:
  purity: 0.005401
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0025_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 1.75
  family_size_sd: 0.84

chromosomes:
  - chr1

seed: 268022
