# varforge config: INS_ML2_VAF1324_0337 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_ins_ml2_vaf1324_0337
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML2_VAF1324_0337
  read_length: 150
  coverage: 5650.9
  platform: illumina

fragment:
  model: normal
  mean: 250.4
  sd: 25.0

quality:
  mean_quality: 33
  tail_decay: 0.0024

tumour:
  purity: 0.264730
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.31
  family_size_sd: 1.02

chromosomes:
  - chr1

seed: 244794
