# varforge config: INVDEL_ML2_VAF0003_0306 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0003_0306
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0003_0306
  read_length: 150
  coverage: 8471.2
  platform: illumina

fragment:
  model: normal
  mean: 251.3
  sd: 31.0

quality:
  mean_quality: 36
  tail_decay: 0.0012

tumour:
  purity: 0.000618
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 4.10
  family_size_sd: 1.38

chromosomes:
  - chr1

seed: 264434
