# varforge config: INVDEL_ML2_VAF0004_0097 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0004_0097
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0004_0097
  read_length: 150
  coverage: 5720.5
  platform: illumina

fragment:
  model: normal
  mean: 173.1
  sd: 20.7

quality:
  mean_quality: 32
  tail_decay: 0.0048

tumour:
  purity: 0.000734
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 4.18
  family_size_sd: 2.34

chromosomes:
  - chr1

seed: 275427
