# varforge config: INVDEL_ML2_VAF0910_0283 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0910_0283
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0910_0283
  read_length: 150
  coverage: 900.9
  platform: illumina

fragment:
  model: normal
  mean: 148.9
  sd: 20.1

quality:
  mean_quality: 32
  tail_decay: 0.0029

tumour:
  purity: 0.182072
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 1.62
  family_size_sd: 0.36

chromosomes:
  - chr1

seed: 211259
