# varforge config: INVDEL_ML2_VAF0182_0155 — VAF 1.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0182_0155
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0182_0155
  read_length: 150
  coverage: 5065.2
  platform: illumina

fragment:
  model: normal
  mean: 210.4
  sd: 20.6

quality:
  mean_quality: 35
  tail_decay: 0.0031

tumour:
  purity: 0.036453
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 3.10
  family_size_sd: 1.85

chromosomes:
  - chr1

seed: 274476
