# varforge config: INVDEL_ML2_VAF0062_0395 — VAF 0.6000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0062_0395
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0062_0395
  read_length: 150
  coverage: 945.5
  platform: illumina

fragment:
  model: normal
  mean: 180.3
  sd: 39.8

quality:
  mean_quality: 33
  tail_decay: 0.0017

tumour:
  purity: 0.012376
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0060_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 4.43
  family_size_sd: 2.15

chromosomes:
  - chr1

seed: 286695
