# varforge config: INVDEL_ML2_VAF0099_0278 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0099_0278
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0099_0278
  read_length: 150
  coverage: 13319.0
  platform: illumina

fragment:
  model: normal
  mean: 139.3
  sd: 30.5

quality:
  mean_quality: 39
  tail_decay: 0.0037

tumour:
  purity: 0.019822
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.13
  family_size_sd: 1.01

chromosomes:
  - chr1

seed: 231367
