# varforge config: INVDEL_ML2_VAF1470_0294 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf1470_0294
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF1470_0294
  read_length: 150
  coverage: 8281.1
  platform: illumina

fragment:
  model: normal
  mean: 277.4
  sd: 38.5

quality:
  mean_quality: 33
  tail_decay: 0.0044

tumour:
  purity: 0.293926
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 1.93
  family_size_sd: 0.92

chromosomes:
  - chr1

seed: 258434
