# varforge config: INVDEL_ML2_VAF0244_0220 — VAF 2.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0244_0220
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0244_0220
  read_length: 150
  coverage: 546.9
  platform: illumina

fragment:
  model: normal
  mean: 142.8
  sd: 26.7

quality:
  mean_quality: 37
  tail_decay: 0.0034

tumour:
  purity: 0.048726
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0250_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 1.57
  family_size_sd: 0.67

chromosomes:
  - chr1

seed: 231677
