# varforge config: INVDEL_ML2_VAF0033_0021 — VAF 0.3500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0033_0021
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0033_0021
  read_length: 150
  coverage: 17953.2
  platform: illumina

fragment:
  model: normal
  mean: 196.6
  sd: 41.6

quality:
  mean_quality: 38
  tail_decay: 0.0036

tumour:
  purity: 0.006597
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 8.08
  family_size_sd: 4.61

chromosomes:
  - chr1

seed: 239681
