# varforge config: INVDEL_ML2_VAF0011_0280 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0011_0280
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0011_0280
  read_length: 150
  coverage: 576.7
  platform: illumina

fragment:
  model: normal
  mean: 135.0
  sd: 30.3

quality:
  mean_quality: 35
  tail_decay: 0.0017

tumour:
  purity: 0.002175
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 7.50
  family_size_sd: 2.26

chromosomes:
  - chr1

seed: 274913
