# varforge config: INVDEL_ML2_VAF0572_0231 — VAF 6.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0572_0231
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0572_0231
  read_length: 150
  coverage: 4872.3
  platform: illumina

fragment:
  model: normal
  mean: 168.0
  sd: 38.6

quality:
  mean_quality: 34
  tail_decay: 0.0039

tumour:
  purity: 0.114461
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0600_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 4.26
  family_size_sd: 1.09

chromosomes:
  - chr1

seed: 208262
