# varforge config: INVDEL_ML2_VAF0137_0011 — VAF 1.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0137_0011
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0137_0011
  read_length: 150
  coverage: 8061.0
  platform: illumina

fragment:
  model: normal
  mean: 148.2
  sd: 40.2

quality:
  mean_quality: 33
  tail_decay: 0.0050

tumour:
  purity: 0.027485
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0125_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 2.25
  family_size_sd: 0.47

chromosomes:
  - chr1

seed: 233675
