# varforge config: INVDEL_ML2_VAF0007_0117 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0007_0117
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0007_0117
  read_length: 150
  coverage: 553.8
  platform: illumina

fragment:
  model: normal
  mean: 257.3
  sd: 20.4

quality:
  mean_quality: 37
  tail_decay: 0.0024

tumour:
  purity: 0.001339
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 1.72
  family_size_sd: 0.44

chromosomes:
  - chr1

seed: 243457
