# varforge config: INVDEL_ML2_VAF0037_0244 — VAF 0.3500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0037_0244
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0037_0244
  read_length: 150
  coverage: 3126.8
  platform: illumina

fragment:
  model: normal
  mean: 159.8
  sd: 27.7

quality:
  mean_quality: 38
  tail_decay: 0.0013

tumour:
  purity: 0.007415
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 8.90
  family_size_sd: 4.44

chromosomes:
  - chr1

seed: 232371
