# varforge config: INVDEL_ML2_VAF0008_0214 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0008_0214
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0008_0214
  read_length: 150
  coverage: 10622.5
  platform: illumina

fragment:
  model: normal
  mean: 195.5
  sd: 23.4

quality:
  mean_quality: 35
  tail_decay: 0.0023

tumour:
  purity: 0.001577
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 3.29
  family_size_sd: 1.66

chromosomes:
  - chr1

seed: 294044
