# varforge config: INVDEL_ML2_VAF0005_0188 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0005_0188
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0005_0188
  read_length: 150
  coverage: 17478.7
  platform: illumina

fragment:
  model: normal
  mean: 194.0
  sd: 43.3

quality:
  mean_quality: 34
  tail_decay: 0.0048

tumour:
  purity: 0.000932
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 7.29
  family_size_sd: 1.51

chromosomes:
  - chr1

seed: 281856
