# varforge config: INVDEL_ML2_VAF0434_0360 — VAF 4.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0434_0360
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0434_0360
  read_length: 150
  coverage: 693.1
  platform: illumina

fragment:
  model: normal
  mean: 175.4
  sd: 15.3

quality:
  mean_quality: 36
  tail_decay: 0.0034

tumour:
  purity: 0.086819
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0400_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 5.20
  family_size_sd: 2.92

chromosomes:
  - chr1

seed: 243442
