# varforge config: INVDEL_ML2_VAF0075_0310 — VAF 0.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_invdel_ml2_vaf0075_0310
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML2_VAF0075_0310
  read_length: 150
  coverage: 14405.1
  platform: illumina

fragment:
  model: normal
  mean: 167.5
  sd: 38.7

quality:
  mean_quality: 39
  tail_decay: 0.0034

tumour:
  purity: 0.015012
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 6.85
  family_size_sd: 3.73

chromosomes:
  - chr1

seed: 217388
