# varforge config: SNV_ML2_VAF1219_0172 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf1219_0172
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF1219_0172
  read_length: 150
  coverage: 3226.4
  platform: illumina

fragment:
  model: normal
  mean: 172.2
  sd: 35.9

quality:
  mean_quality: 38
  tail_decay: 0.0037

tumour:
  purity: 0.243899
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 2.26
  family_size_sd: 0.77

chromosomes:
  - chr1

seed: 236038
