# varforge config: SNV_ML2_VAF0019_0691 — VAF 0.2000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0019_0691
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0019_0691
  read_length: 150
  coverage: 12693.6
  platform: illumina

fragment:
  model: normal
  mean: 197.5
  sd: 43.3

quality:
  mean_quality: 33
  tail_decay: 0.0047

tumour:
  purity: 0.003815
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0020_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 4.57
  family_size_sd: 1.75

chromosomes:
  - chr1

seed: 251571
