# varforge config: SNV_ML2_VAF0014_0859 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0014_0859
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0014_0859
  read_length: 150
  coverage: 17514.0
  platform: illumina

fragment:
  model: normal
  mean: 212.3
  sd: 17.3

quality:
  mean_quality: 36
  tail_decay: 0.0025

tumour:
  purity: 0.002793
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 2.50
  family_size_sd: 1.03

chromosomes:
  - chr1

seed: 299061
