# varforge config: SNV_ML2_VAF0003_0516 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0003_0516
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0003_0516
  read_length: 150
  coverage: 502.9
  platform: illumina

fragment:
  model: normal
  mean: 249.9
  sd: 50.0

quality:
  mean_quality: 34
  tail_decay: 0.0023

tumour:
  purity: 0.000696
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 4.91
  family_size_sd: 1.21

chromosomes:
  - chr1

seed: 241093
