# varforge config: SNV_ML2_VAF0007_0193 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0007_0193
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0007_0193
  read_length: 150
  coverage: 988.6
  platform: illumina

fragment:
  model: normal
  mean: 187.5
  sd: 30.6

quality:
  mean_quality: 33
  tail_decay: 0.0023

tumour:
  purity: 0.001438
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 2.77
  family_size_sd: 0.83

chromosomes:
  - chr1

seed: 288527
