# varforge config: SNV_ML2_VAF0037_0388 — VAF 0.3500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0037_0388
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0037_0388
  read_length: 150
  coverage: 2640.6
  platform: illumina

fragment:
  model: normal
  mean: 210.2
  sd: 37.4

quality:
  mean_quality: 36
  tail_decay: 0.0040

tumour:
  purity: 0.007409
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0035_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 2.73
  family_size_sd: 0.97

chromosomes:
  - chr1

seed: 292475
