# varforge config: SNV_ML2_VAF0261_0169 — VAF 2.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0261_0169
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0261_0169
  read_length: 150
  coverage: 1584.0
  platform: illumina

fragment:
  model: normal
  mean: 149.6
  sd: 28.0

quality:
  mean_quality: 36
  tail_decay: 0.0023

tumour:
  purity: 0.052118
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0250_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 6.04
  family_size_sd: 3.29

chromosomes:
  - chr1

seed: 227309
