# varforge config: SNV_ML2_VAF0031_0755 — VAF 0.3000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0031_0755
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0031_0755
  read_length: 150
  coverage: 14709.6
  platform: illumina

fragment:
  model: normal
  mean: 139.3
  sd: 43.1

quality:
  mean_quality: 31
  tail_decay: 0.0034

tumour:
  purity: 0.006262
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0030_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 8.12
  family_size_sd: 3.88

chromosomes:
  - chr1

seed: 272629
