# varforge config: SNV_ML2_VAF0017_0424 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0017_0424
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0017_0424
  read_length: 150
  coverage: 17466.9
  platform: illumina

fragment:
  model: normal
  mean: 216.2
  sd: 24.1

quality:
  mean_quality: 34
  tail_decay: 0.0014

tumour:
  purity: 0.003345
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 4.74
  family_size_sd: 1.32

chromosomes:
  - chr1

seed: 205799
