# varforge config: SNV_ML2_VAF0745_0088 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0745_0088
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0745_0088
  read_length: 150
  coverage: 5048.2
  platform: illumina

fragment:
  model: normal
  mean: 140.3
  sd: 37.1

quality:
  mean_quality: 39
  tail_decay: 0.0050

tumour:
  purity: 0.149046
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.79
  family_size_sd: 1.58

chromosomes:
  - chr1

seed: 296916
