# varforge config: SNV_ML2_VAF0409_0069 — VAF 4.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0409_0069
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0409_0069
  read_length: 150
  coverage: 4680.9
  platform: illumina

fragment:
  model: normal
  mean: 266.3
  sd: 25.4

quality:
  mean_quality: 36
  tail_decay: 0.0027

tumour:
  purity: 0.081722
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0400_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.30
  family_size_sd: 0.94

chromosomes:
  - chr1

seed: 202566
