# varforge config: SNV_ML2_VAF0011_0399 — VAF 0.1000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0011_0399
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0011_0399
  read_length: 150
  coverage: 8536.4
  platform: illumina

fragment:
  model: normal
  mean: 200.8
  sd: 42.1

quality:
  mean_quality: 34
  tail_decay: 0.0019

tumour:
  purity: 0.002251
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 1.61
  family_size_sd: 0.49

chromosomes:
  - chr1

seed: 216890
