# varforge config: SNV_ML2_VAF0004_0799 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0004_0799
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0004_0799
  read_length: 150
  coverage: 7225.7
  platform: illumina

fragment:
  model: normal
  mean: 214.3
  sd: 21.6

quality:
  mean_quality: 32
  tail_decay: 0.0032

tumour:
  purity: 0.000789
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 3.97
  family_size_sd: 2.09

chromosomes:
  - chr1

seed: 265260
