# varforge config: SNV_ML2_VAF0072_0038 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0072_0038
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0072_0038
  read_length: 150
  coverage: 4679.0
  platform: illumina

fragment:
  model: normal
  mean: 136.7
  sd: 30.3

quality:
  mean_quality: 35
  tail_decay: 0.0042

tumour:
  purity: 0.014403
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0075_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 3.11
  family_size_sd: 1.34

chromosomes:
  - chr1

seed: 292592
