# varforge config: SNV_ML2_VAF0239_0005 — VAF 2.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0239_0005
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0239_0005
  read_length: 150
  coverage: 4206.5
  platform: illumina

fragment:
  model: normal
  mean: 277.8
  sd: 44.9

quality:
  mean_quality: 39
  tail_decay: 0.0025

tumour:
  purity: 0.047838
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0250_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 1.64
  family_size_sd: 0.48

chromosomes:
  - chr1

seed: 275275
