# varforge config: SNV_ML2_VAF0017_0140 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0017_0140
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0017_0140
  read_length: 150
  coverage: 2745.4
  platform: illumina

fragment:
  model: normal
  mean: 252.5
  sd: 43.0

quality:
  mean_quality: 31
  tail_decay: 0.0020

tumour:
  purity: 0.003457
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 3.10
  family_size_sd: 1.27

chromosomes:
  - chr1

seed: 265349
