# varforge config: SNV_ML2_VAF0003_0658 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0003_0658
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0003_0658
  read_length: 150
  coverage: 10347.8
  platform: illumina

fragment:
  model: normal
  mean: 249.8
  sd: 16.9

quality:
  mean_quality: 39
  tail_decay: 0.0037

tumour:
  purity: 0.000684
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 9.39
  family_size_sd: 4.15

chromosomes:
  - chr1

seed: 248574
