# varforge config: SNV_ML2_VAF0011_0783 — VAF 0.1000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0011_0783
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0011_0783
  read_length: 150
  coverage: 18589.4
  platform: illumina

fragment:
  model: normal
  mean: 201.2
  sd: 26.5

quality:
  mean_quality: 40
  tail_decay: 0.0036

tumour:
  purity: 0.002134
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 3.15
  family_size_sd: 1.30

chromosomes:
  - chr1

seed: 242607
