# varforge config: SNV_ML2_VAF0537_0032 — VAF 5.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0537_0032
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0537_0032
  read_length: 150
  coverage: 3741.4
  platform: illumina

fragment:
  model: normal
  mean: 136.3
  sd: 27.8

quality:
  mean_quality: 39
  tail_decay: 0.0049

tumour:
  purity: 0.107324
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0500_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 4.53
  family_size_sd: 1.17

chromosomes:
  - chr1

seed: 287671
