# varforge config: SNV_ML2_VAF0040_0049 — VAF 0.4000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0040_0049
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0040_0049
  read_length: 150
  coverage: 3700.5
  platform: illumina

fragment:
  model: normal
  mean: 271.9
  sd: 15.7

quality:
  mean_quality: 39
  tail_decay: 0.0033

tumour:
  purity: 0.007949
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0040_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.22
  family_size_sd: 0.82

chromosomes:
  - chr1

seed: 249270
