# varforge config: SNV_ML2_VAF0005_0765 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0005_0765
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0005_0765
  read_length: 150
  coverage: 1906.4
  platform: illumina

fragment:
  model: normal
  mean: 196.1
  sd: 37.1

quality:
  mean_quality: 39
  tail_decay: 0.0024

tumour:
  purity: 0.000949
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 1.59
  family_size_sd: 0.39

chromosomes:
  - chr1

seed: 216166
