# varforge config: SNV_ML2_VAF0016_0227 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0016_0227
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0016_0227
  read_length: 150
  coverage: 557.7
  platform: illumina

fragment:
  model: normal
  mean: 213.0
  sd: 28.1

quality:
  mean_quality: 32
  tail_decay: 0.0033

tumour:
  purity: 0.003280
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 9.86
  family_size_sd: 3.91

chromosomes:
  - chr1

seed: 243179
