# varforge config: SNV_ML2_VAF0034_0643 — VAF 0.3500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0034_0643
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0034_0643
  read_length: 150
  coverage: 2014.3
  platform: illumina

fragment:
  model: normal
  mean: 233.6
  sd: 22.2

quality:
  mean_quality: 35
  tail_decay: 0.0042

tumour:
  purity: 0.006785
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 4.44
  family_size_sd: 2.33

chromosomes:
  - chr1

seed: 276679
