# varforge config: SNV_ML2_VAF0008_0316 — VAF 0.1000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0008_0316
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0008_0316
  read_length: 150
  coverage: 4008.0
  platform: illumina

fragment:
  model: normal
  mean: 181.6
  sd: 34.0

quality:
  mean_quality: 40
  tail_decay: 0.0034

tumour:
  purity: 0.001535
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 5.62
  family_size_sd: 1.34

chromosomes:
  - chr1

seed: 209035
