# varforge config: SNV_ML2_VAF0823_0096 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0823_0096
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0823_0096
  read_length: 150
  coverage: 5075.3
  platform: illumina

fragment:
  model: normal
  mean: 135.0
  sd: 27.8

quality:
  mean_quality: 31
  tail_decay: 0.0046

tumour:
  purity: 0.164593
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0800_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 5.11
  family_size_sd: 1.65

chromosomes:
  - chr1

seed: 211590
