# varforge config: SNV_ML2_VAF0016_0308 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0016_0308
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0016_0308
  read_length: 150
  coverage: 2597.2
  platform: illumina

fragment:
  model: normal
  mean: 248.1
  sd: 40.2

quality:
  mean_quality: 30
  tail_decay: 0.0028

tumour:
  purity: 0.003119
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 2.41
  family_size_sd: 0.55

chromosomes:
  - chr1

seed: 240441
