# varforge config: SNV_ML2_VAF1308_0015 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf1308_0015
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF1308_0015
  read_length: 150
  coverage: 10145.8
  platform: illumina

fragment:
  model: normal
  mean: 201.3
  sd: 34.2

quality:
  mean_quality: 33
  tail_decay: 0.0045

tumour:
  purity: 0.261639
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 4.12
  family_size_sd: 1.03

chromosomes:
  - chr1

seed: 288084
