# varforge config: SNV_ML2_VAF0498_0100 — VAF 5.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0498_0100
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0498_0100
  read_length: 150
  coverage: 4319.9
  platform: illumina

fragment:
  model: normal
  mean: 200.7
  sd: 36.7

quality:
  mean_quality: 39
  tail_decay: 0.0023

tumour:
  purity: 0.099502
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0500_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 8.93
  family_size_sd: 2.17

chromosomes:
  - chr1

seed: 288812
