# varforge config: SNV_ML2_VAF0086_0807 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0086_0807
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0086_0807
  read_length: 150
  coverage: 1222.0
  platform: illumina

fragment:
  model: normal
  mean: 250.2
  sd: 39.4

quality:
  mean_quality: 32
  tail_decay: 0.0045

tumour:
  purity: 0.017129
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 8.38
  family_size_sd: 3.90

chromosomes:
  - chr1

seed: 262312
