# varforge config: SNV_ML2_VAF0127_0371 — VAF 1.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0127_0371
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0127_0371
  read_length: 150
  coverage: 832.4
  platform: illumina

fragment:
  model: normal
  mean: 259.1
  sd: 39.9

quality:
  mean_quality: 39
  tail_decay: 0.0035

tumour:
  purity: 0.025372
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 8.06
  family_size_sd: 3.26

chromosomes:
  - chr1

seed: 216081
