# varforge config: SNV_ML2_VAF0045_0676 — VAF 0.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0045_0676
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0045_0676
  read_length: 150
  coverage: 3366.6
  platform: illumina

fragment:
  model: normal
  mean: 244.6
  sd: 20.3

quality:
  mean_quality: 39
  tail_decay: 0.0036

tumour:
  purity: 0.009001
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0050_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.05
  family_size_sd: 1.01

chromosomes:
  - chr1

seed: 236093
