# varforge config: SNV_ML2_VAF0166_0817 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0166_0817
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0166_0817
  read_length: 150
  coverage: 6551.8
  platform: illumina

fragment:
  model: normal
  mean: 152.1
  sd: 23.7

quality:
  mean_quality: 36
  tail_decay: 0.0037

tumour:
  purity: 0.033105
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 2.46
  family_size_sd: 0.94

chromosomes:
  - chr1

seed: 205776
