# varforge config: SNV_ML2_VAF0059_0351 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0059_0351
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0059_0351
  read_length: 150
  coverage: 6331.6
  platform: illumina

fragment:
  model: normal
  mean: 266.0
  sd: 44.2

quality:
  mean_quality: 37
  tail_decay: 0.0016

tumour:
  purity: 0.011897
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0060_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 2.34
  family_size_sd: 0.48

chromosomes:
  - chr1

seed: 255092
