# varforge config: SNV_ML2_VAF0469_0744 — VAF 5.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0469_0744
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0469_0744
  read_length: 150
  coverage: 1838.6
  platform: illumina

fragment:
  model: normal
  mean: 255.9
  sd: 43.4

quality:
  mean_quality: 40
  tail_decay: 0.0015

tumour:
  purity: 0.093718
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0500_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 7.21
  family_size_sd: 2.47

chromosomes:
  - chr1

seed: 271550
