# varforge config: SNV_ML2_VAF0082_0412 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0082_0412
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0082_0412
  read_length: 150
  coverage: 12740.4
  platform: illumina

fragment:
  model: normal
  mean: 149.5
  sd: 36.1

quality:
  mean_quality: 38
  tail_decay: 0.0046

tumour:
  purity: 0.016310
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 6.25
  family_size_sd: 1.48

chromosomes:
  - chr1

seed: 224591
