# varforge config: SNV_ML2_VAF0133_0132 — VAF 1.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0133_0132
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0133_0132
  read_length: 150
  coverage: 3455.9
  platform: illumina

fragment:
  model: normal
  mean: 191.3
  sd: 26.8

quality:
  mean_quality: 36
  tail_decay: 0.0042

tumour:
  purity: 0.026546
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0125_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 2.99
  family_size_sd: 1.70

chromosomes:
  - chr1

seed: 210287
