# varforge config: SNV_ML2_VAF0043_0883 — VAF 0.4000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0043_0883
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0043_0883
  read_length: 150
  coverage: 627.0
  platform: illumina

fragment:
  model: normal
  mean: 172.1
  sd: 27.3

quality:
  mean_quality: 34
  tail_decay: 0.0023

tumour:
  purity: 0.008527
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0040_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 1.65
  family_size_sd: 0.40

chromosomes:
  - chr1

seed: 261343
