# varforge config: SNV_ML2_VAF0005_0857 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0005_0857
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0005_0857
  read_length: 150
  coverage: 2187.2
  platform: illumina

fragment:
  model: normal
  mean: 210.4
  sd: 17.5

quality:
  mean_quality: 37
  tail_decay: 0.0050

tumour:
  purity: 0.001007
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.43
  family_size_sd: 0.90

chromosomes:
  - chr1

seed: 227701
