# varforge config: SNV_ML2_VAF0005_0547 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0005_0547
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0005_0547
  read_length: 150
  coverage: 2778.6
  platform: illumina

fragment:
  model: normal
  mean: 224.6
  sd: 38.2

quality:
  mean_quality: 37
  tail_decay: 0.0037

tumour:
  purity: 0.000976
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 8.12
  family_size_sd: 1.91

chromosomes:
  - chr1

seed: 213676
