# varforge config: SNV_ML2_VAF0010_0398 — VAF 0.1000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0010_0398
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0010_0398
  read_length: 150
  coverage: 13393.1
  platform: illumina

fragment:
  model: normal
  mean: 263.8
  sd: 44.7

quality:
  mean_quality: 36
  tail_decay: 0.0043

tumour:
  purity: 0.002034
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 6.03
  family_size_sd: 2.72

chromosomes:
  - chr1

seed: 210829
