# varforge config: SNV_ML2_VAF0784_0532 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0784_0532
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0784_0532
  read_length: 150
  coverage: 849.6
  platform: illumina

fragment:
  model: normal
  mean: 234.9
  sd: 38.3

quality:
  mean_quality: 38
  tail_decay: 0.0045

tumour:
  purity: 0.156899
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0800_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.45
  family_size_sd: 0.85

chromosomes:
  - chr1

seed: 211530
