# varforge config: SNV_ML2_VAF0165_0598 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0165_0598
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0165_0598
  read_length: 150
  coverage: 2570.8
  platform: illumina

fragment:
  model: normal
  mean: 255.2
  sd: 33.2

quality:
  mean_quality: 33
  tail_decay: 0.0033

tumour:
  purity: 0.032971
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0175_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 2.61
  family_size_sd: 0.59

chromosomes:
  - chr1

seed: 244291
