# varforge config: SNV_ML2_VAF0006_0668 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0006_0668
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0006_0668
  read_length: 150
  coverage: 16463.1
  platform: illumina

fragment:
  model: normal
  mean: 254.1
  sd: 32.3

quality:
  mean_quality: 32
  tail_decay: 0.0018

tumour:
  purity: 0.001244
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 5.86
  family_size_sd: 2.19

chromosomes:
  - chr1

seed: 231664
