# varforge config: SNV_ML2_VAF0017_0116 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0017_0116
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0017_0116
  read_length: 150
  coverage: 763.9
  platform: illumina

fragment:
  model: normal
  mean: 276.2
  sd: 43.6

quality:
  mean_quality: 36
  tail_decay: 0.0036

tumour:
  purity: 0.003388
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 2.30
  family_size_sd: 0.86

chromosomes:
  - chr1

seed: 212653
