# varforge config: SNV_ML2_VAF0251_0772 — VAF 2.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0251_0772
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0251_0772
  read_length: 150
  coverage: 967.7
  platform: illumina

fragment:
  model: normal
  mean: 201.1
  sd: 35.3

quality:
  mean_quality: 36
  tail_decay: 0.0042

tumour:
  purity: 0.050250
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0250_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 4.06
  family_size_sd: 1.60

chromosomes:
  - chr1

seed: 279701
