# varforge config: SNV_ML2_VAF0162_0544 — VAF 1.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_snv_ml2_vaf0162_0544
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML2_VAF0162_0544
  read_length: 150
  coverage: 683.3
  platform: illumina

fragment:
  model: normal
  mean: 269.5
  sd: 36.8

quality:
  mean_quality: 35
  tail_decay: 0.0027

tumour:
  purity: 0.032475
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0150_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.30
  family_size_sd: 1.26

chromosomes:
  - chr1

seed: 202952
