# varforge config: SV_ML2_VAF0457_0280 — VAF 5.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0457_0280
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0457_0280
  read_length: 150
  coverage: 779.8
  platform: illumina

fragment:
  model: normal
  mean: 153.8
  sd: 41.0

quality:
  mean_quality: 35
  tail_decay: 0.0021

tumour:
  purity: 0.091343
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0500_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.31
  family_size_sd: 0.47

chromosomes:
  - chr1

seed: 270622
