# varforge config: SV_ML2_VAF0177_0253 — VAF 1.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0177_0253
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0177_0253
  read_length: 150
  coverage: 1014.7
  platform: illumina

fragment:
  model: normal
  mean: 205.0
  sd: 45.9

quality:
  mean_quality: 35
  tail_decay: 0.0024

tumour:
  purity: 0.035426
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0175_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.76
  family_size_sd: 1.05

chromosomes:
  - chr1

seed: 267872
