# varforge config: SV_ML2_VAF0986_0115 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0986_0115
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0986_0115
  read_length: 150
  coverage: 828.6
  platform: illumina

fragment:
  model: normal
  mean: 148.7
  sd: 15.3

quality:
  mean_quality: 32
  tail_decay: 0.0047

tumour:
  purity: 0.197141
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 6.44
  family_size_sd: 1.76

chromosomes:
  - chr1

seed: 243576
