# varforge config: SV_ML2_VAF1369_0348 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf1369_0348
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF1369_0348
  read_length: 150
  coverage: 2008.5
  platform: illumina

fragment:
  model: normal
  mean: 253.2
  sd: 35.6

quality:
  mean_quality: 37
  tail_decay: 0.0042

tumour:
  purity: 0.273752
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 8.41
  family_size_sd: 4.87

chromosomes:
  - chr1

seed: 267384
