# varforge config: SV_ML2_VAF0061_0065 — VAF 0.6000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0061_0065
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0061_0065
  read_length: 150
  coverage: 12063.5
  platform: illumina

fragment:
  model: normal
  mean: 219.7
  sd: 27.3

quality:
  mean_quality: 36
  tail_decay: 0.0035

tumour:
  purity: 0.012202
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0060_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 5.59
  family_size_sd: 2.90

chromosomes:
  - chr1

seed: 253949
