# varforge config: SV_ML2_VAF0028_0171 — VAF 0.3000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0028_0171
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0028_0171
  read_length: 150
  coverage: 647.5
  platform: illumina

fragment:
  model: normal
  mean: 131.5
  sd: 31.3

quality:
  mean_quality: 36
  tail_decay: 0.0011

tumour:
  purity: 0.005634
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0030_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 3.26
  family_size_sd: 1.36

chromosomes:
  - chr1

seed: 224477
