# varforge config: SV_ML2_VAF0273_0139 — VAF 2.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0273_0139
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0273_0139
  read_length: 150
  coverage: 679.1
  platform: illumina

fragment:
  model: normal
  mean: 181.3
  sd: 30.2

quality:
  mean_quality: 35
  tail_decay: 0.0041

tumour:
  purity: 0.054692
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0250_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 5.03
  family_size_sd: 1.43

chromosomes:
  - chr1

seed: 235996
