# varforge config: SV_ML2_VAF0041_0209 — VAF 0.4000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0041_0209
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0041_0209
  read_length: 150
  coverage: 3921.5
  platform: illumina

fragment:
  model: normal
  mean: 154.5
  sd: 26.1

quality:
  mean_quality: 31
  tail_decay: 0.0037

tumour:
  purity: 0.008255
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0040_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 3.81
  family_size_sd: 1.39

chromosomes:
  - chr1

seed: 232168
