# varforge config: SV_ML2_VAF0784_0094 — VAF 8.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0784_0094
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0784_0094
  read_length: 150
  coverage: 2236.2
  platform: illumina

fragment:
  model: normal
  mean: 193.4
  sd: 37.0

quality:
  mean_quality: 34
  tail_decay: 0.0033

tumour:
  purity: 0.156853
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 3.82
  family_size_sd: 0.91

chromosomes:
  - chr1

seed: 299226
