# varforge config: SV_ML2_VAF0662_0260 — VAF 7.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0662_0260
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0662_0260
  read_length: 150
  coverage: 3752.2
  platform: illumina

fragment:
  model: normal
  mean: 268.2
  sd: 43.2

quality:
  mean_quality: 31
  tail_decay: 0.0047

tumour:
  purity: 0.132375
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0700_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 3.53
  family_size_sd: 1.95

chromosomes:
  - chr1

seed: 232959
