# varforge config: SV_ML2_VAF0121_0277 — VAF 1.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0121_0277
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0121_0277
  read_length: 150
  coverage: 2060.9
  platform: illumina

fragment:
  model: normal
  mean: 160.5
  sd: 30.7

quality:
  mean_quality: 36
  tail_decay: 0.0042

tumour:
  purity: 0.024257
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 7.77
  family_size_sd: 3.55

chromosomes:
  - chr1

seed: 207249
