# varforge config: SV_ML2_VAF0011_0165 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0011_0165
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0011_0165
  read_length: 150
  coverage: 722.3
  platform: illumina

fragment:
  model: normal
  mean: 256.0
  sd: 37.5

quality:
  mean_quality: 31
  tail_decay: 0.0029

tumour:
  purity: 0.002284
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 2.51
  family_size_sd: 1.50

chromosomes:
  - chr1

seed: 292041
