# varforge config: SV_ML2_VAF1025_0300 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf1025_0300
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF1025_0300
  read_length: 150
  coverage: 1510.3
  platform: illumina

fragment:
  model: normal
  mean: 265.0
  sd: 25.1

quality:
  mean_quality: 39
  tail_decay: 0.0018

tumour:
  purity: 0.204951
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 5.83
  family_size_sd: 2.07

chromosomes:
  - chr1

seed: 289419
