# varforge config: SV_ML2_VAF0005_0303 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0005_0303
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0005_0303
  read_length: 150
  coverage: 537.8
  platform: illumina

fragment:
  model: normal
  mean: 158.3
  sd: 25.5

quality:
  mean_quality: 32
  tail_decay: 0.0045

tumour:
  purity: 0.001027
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 7.47
  family_size_sd: 3.35

chromosomes:
  - chr1

seed: 224592
