# varforge config: SV_ML2_VAF0013_0251 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0013_0251
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0013_0251
  read_length: 150
  coverage: 4429.0
  platform: illumina

fragment:
  model: normal
  mean: 246.6
  sd: 24.1

quality:
  mean_quality: 33
  tail_decay: 0.0011

tumour:
  purity: 0.002565
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 1.67
  family_size_sd: 0.56

chromosomes:
  - chr1

seed: 228633
