# varforge config: SV_ML2_VAF1155_0263 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf1155_0263
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF1155_0263
  read_length: 150
  coverage: 3664.1
  platform: illumina

fragment:
  model: normal
  mean: 169.0
  sd: 20.5

quality:
  mean_quality: 33
  tail_decay: 0.0039

tumour:
  purity: 0.230941
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 1.60
  family_size_sd: 0.57

chromosomes:
  - chr1

seed: 238965
