# varforge config: SV_ML2_VAF0005_0119 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0005_0119
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0005_0119
  read_length: 150
  coverage: 15478.0
  platform: illumina

fragment:
  model: normal
  mean: 151.5
  sd: 48.9

quality:
  mean_quality: 35
  tail_decay: 0.0027

tumour:
  purity: 0.000915
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 5.85
  family_size_sd: 2.27

chromosomes:
  - chr1

seed: 299389
