# varforge config: SV_ML2_VAF0004_0320 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0004_0320
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0004_0320
  read_length: 150
  coverage: 6479.6
  platform: illumina

fragment:
  model: normal
  mean: 211.8
  sd: 29.1

quality:
  mean_quality: 37
  tail_decay: 0.0011

tumour:
  purity: 0.000864
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 5.13
  family_size_sd: 2.18

chromosomes:
  - chr1

seed: 288865
