# varforge config: SV_ML2_VAF0007_0386 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0007_0386
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0007_0386
  read_length: 150
  coverage: 5282.5
  platform: illumina

fragment:
  model: normal
  mean: 153.7
  sd: 22.0

quality:
  mean_quality: 39
  tail_decay: 0.0040

tumour:
  purity: 0.001461
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 1.94
  family_size_sd: 0.86

chromosomes:
  - chr1

seed: 201475
