# varforge config: SV_ML2_VAF0886_0372 — VAF 8.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0886_0372
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0886_0372
  read_length: 150
  coverage: 3326.7
  platform: illumina

fragment:
  model: normal
  mean: 224.3
  sd: 39.3

quality:
  mean_quality: 30
  tail_decay: 0.0028

tumour:
  purity: 0.177265
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 4.21
  family_size_sd: 1.51

chromosomes:
  - chr1

seed: 235923
