# varforge config: SV_ML2_VAF0089_0151 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0089_0151
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0089_0151
  read_length: 150
  coverage: 11726.0
  platform: illumina

fragment:
  model: normal
  mean: 191.5
  sd: 27.0

quality:
  mean_quality: 32
  tail_decay: 0.0017

tumour:
  purity: 0.017713
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0100_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 3.34
  family_size_sd: 1.69

chromosomes:
  - chr1

seed: 297387
