# varforge config: SV_ML2_VAF0760_0197 — VAF 8.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0760_0197
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0760_0197
  read_length: 150
  coverage: 1422.2
  platform: illumina

fragment:
  model: normal
  mean: 152.2
  sd: 16.9

quality:
  mean_quality: 31
  tail_decay: 0.0016

tumour:
  purity: 0.151976
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.52
  family_size_sd: 0.91

chromosomes:
  - chr1

seed: 295217
