# varforge config: SV_ML2_VAF0971_0170 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0971_0170
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0971_0170
  read_length: 150
  coverage: 614.9
  platform: illumina

fragment:
  model: normal
  mean: 246.9
  sd: 23.3

quality:
  mean_quality: 39
  tail_decay: 0.0027

tumour:
  purity: 0.194135
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 6.58
  family_size_sd: 1.40

chromosomes:
  - chr1

seed: 246196
