# varforge config: SV_ML2_VAF0110_0322 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0110_0322
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0110_0322
  read_length: 150
  coverage: 16237.6
  platform: illumina

fragment:
  model: normal
  mean: 142.0
  sd: 49.8

quality:
  mean_quality: 38
  tail_decay: 0.0047

tumour:
  purity: 0.022087
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.10
  family_size_sd: 1.12

chromosomes:
  - chr1

seed: 257492
