# varforge config: SV_ML2_VAF1012_0398 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf1012_0398
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF1012_0398
  read_length: 150
  coverage: 17540.2
  platform: illumina

fragment:
  model: normal
  mean: 194.5
  sd: 28.6

quality:
  mean_quality: 31
  tail_decay: 0.0019

tumour:
  purity: 0.202468
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 7.49
  family_size_sd: 2.71

chromosomes:
  - chr1

seed: 261818
