# varforge config: SV_ML2_VAF0006_0048 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/sim_sv_ml2_vaf0006_0048
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML2_VAF0006_0048
  read_length: 150
  coverage: 1076.6
  platform: illumina

fragment:
  model: normal
  mean: 192.4
  sd: 41.0

quality:
  mean_quality: 37
  tail_decay: 0.0036

tumour:
  purity: 0.001172
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.66
  family_size_sd: 1.24

chromosomes:
  - chr1

seed: 273556
