#!/bin/bash
# claude_loop.sh — run Claude Code autonomously on queued tasks
#
# Usage:
#   ./claude_loop.sh              # run all queued tasks (default max 10)
#   ./claude_loop.sh 5            # run at most 5 tasks
#   ./claude_loop.sh --parallel 3 # run up to 3 tasks in parallel
#
# Tasks are picked from docs/claudeloop/queue/ in filename sort order.
# Each task is moved to in_progress/, run via `claude --print`, then:
#   - If cargo test + clippy pass → committed and moved to done/
#   - If they fail → reverted and moved to needs_review/

set -euo pipefail

TASK_DIR="docs/claudeloop"
LOG_DIR="logs/claude"
MAX_TASKS="${1:-10}"
TASKS_DONE=0

mkdir -p "${LOG_DIR}"
mkdir -p "${TASK_DIR}/in_progress"
mkdir -p "${TASK_DIR}/done"
mkdir -p "${TASK_DIR}/needs_review"

echo "$(date): Claude loop starting. Max tasks: ${MAX_TASKS}"
echo "$(date): Queue contents:"
ls "${TASK_DIR}/queue/"*.md 2>/dev/null || echo "  (empty)"

while [ ${TASKS_DONE} -lt ${MAX_TASKS} ]; do
    # Pick next task
    NEXT_TASK=$(ls "${TASK_DIR}/queue/"*.md 2>/dev/null | sort | head -1)

    if [ -z "${NEXT_TASK}" ]; then
        echo "$(date): No tasks in queue. Stopping."
        break
    fi

    TASK_NAME=$(basename "${NEXT_TASK}" .md)
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    LOG_FILE="${LOG_DIR}/${TIMESTAMP}_${TASK_NAME}.log"

    echo ""
    echo "========================================"
    echo "$(date): Starting task ${TASKS_DONE+1}/${MAX_TASKS}: ${TASK_NAME}"
    echo "========================================"

    # Move to in_progress
    mv "${NEXT_TASK}" "${TASK_DIR}/in_progress/"

    # Snapshot current state for revert
    BEFORE_SHA=$(git rev-parse HEAD 2>/dev/null || echo "none")

    # Run Claude Code on this task
    claude --print \
        "You are working on the kam project. Read CLAUDE.md first for project context.

Complete the task described in ${TASK_DIR}/in_progress/${TASK_NAME}.md.
Follow all rules in CLAUDE.md strictly.

When done:
1. Run \`cargo test\` for the relevant crate(s)
2. Run \`cargo clippy -- -D warnings\` for the relevant crate(s)
3. If both pass, the task is complete.
4. If they fail after 3 attempts, add a // TODO comment explaining what failed and move on.

Do NOT modify any files in kam-core unless the task explicitly says to.
Do NOT modify any files in docs/." \
        2>&1 | tee "${LOG_FILE}"

    EXIT_CODE=${PIPESTATUS[0]}

    # Verify cargo test still passes
    echo ""
    echo "$(date): Verifying tests after ${TASK_NAME}..."
    if cargo test --quiet 2>> "${LOG_FILE}"; then
        echo "$(date): Tests PASS."

        # Verify clippy
        if cargo clippy -- -D warnings 2>> "${LOG_FILE}"; then
            echo "$(date): Clippy PASS. Committing."

            git add -A
            git commit -m "$(cat <<EOF
implement ${TASK_NAME}

Auto-generated by Claude Code loop
Task: ${TASK_NAME}
Log: ${LOG_FILE}

Co-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>
EOF
)"
            mv "${TASK_DIR}/in_progress/${TASK_NAME}.md" "${TASK_DIR}/done/"
        else
            echo "$(date): Clippy FAILED. Moving to needs_review."
            git stash --include-untracked -m "failed-clippy-${TASK_NAME}" 2>/dev/null || true
            mv "${TASK_DIR}/in_progress/${TASK_NAME}.md" \
               "${TASK_DIR}/needs_review/${TASK_NAME}.md"
        fi
    else
        echo "$(date): Tests FAILED after ${TASK_NAME}. Reverting."
        git stash --include-untracked -m "failed-tests-${TASK_NAME}" 2>/dev/null || true
        mv "${TASK_DIR}/in_progress/${TASK_NAME}.md" \
           "${TASK_DIR}/needs_review/${TASK_NAME}.md"
    fi

    TASKS_DONE=$((TASKS_DONE + 1))

    # Brief pause
    sleep 5
done

echo ""
echo "========================================"
echo "$(date): Loop complete. Tasks done: ${TASKS_DONE}"
echo "Queue remaining: $(ls "${TASK_DIR}/queue/"*.md 2>/dev/null | wc -l)"
echo "Needs review: $(ls "${TASK_DIR}/needs_review/"*.md 2>/dev/null | wc -l)"
echo "========================================"
