# varforge config: INDEL_ML3_TRAIN_VAF1071_0704 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1071_0704
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1071_0704
  read_length: 150
  coverage: 818.8
  platform: illumina

fragment:
  model: normal
  mean: 221.2
  sd: 27.2

quality:
  mean_quality: 40
  tail_decay: 0.0049

tumour:
  purity: 0.214159
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.26
  family_size_sd: 0.80

chromosomes:
  - chr1

seed: 462970
