# varforge config: INDEL_ML3_TRAIN_VAF0017_1184 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0017_1184
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0017_1184
  read_length: 150
  coverage: 1020.2
  platform: illumina

fragment:
  model: normal
  mean: 249.9
  sd: 18.1

quality:
  mean_quality: 33
  tail_decay: 0.0034

tumour:
  purity: 0.003471
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 1.86
  family_size_sd: 0.42

chromosomes:
  - chr1

seed: 430292
