# varforge config: INDEL_ML3_TRAIN_VAF0103_1023 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0103_1023
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0103_1023
  read_length: 150
  coverage: 7244.2
  platform: illumina

fragment:
  model: normal
  mean: 257.9
  sd: 37.3

quality:
  mean_quality: 36
  tail_decay: 0.0022

tumour:
  purity: 0.020603
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 5.90
  family_size_sd: 3.50

chromosomes:
  - chr1

seed: 469813
