# varforge config: INDEL_ML3_TRAIN_VAF1180_0728 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1180_0728
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1180_0728
  read_length: 150
  coverage: 3819.5
  platform: illumina

fragment:
  model: normal
  mean: 222.6
  sd: 49.9

quality:
  mean_quality: 30
  tail_decay: 0.0030

tumour:
  purity: 0.236078
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 6.62
  family_size_sd: 1.50

chromosomes:
  - chr1

seed: 459703
