# varforge config: INDEL_ML3_TRAIN_VAF0153_0536 — VAF 1.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0153_0536
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0153_0536
  read_length: 150
  coverage: 951.1
  platform: illumina

fragment:
  model: normal
  mean: 136.3
  sd: 39.3

quality:
  mean_quality: 35
  tail_decay: 0.0021

tumour:
  purity: 0.030597
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0150_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 9.44
  family_size_sd: 4.65

chromosomes:
  - chr1

seed: 488811
