# varforge config: INDEL_ML3_TRAIN_VAF0023_1598 — VAF 0.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0023_1598
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0023_1598
  read_length: 150
  coverage: 3743.7
  platform: illumina

fragment:
  model: normal
  mean: 171.9
  sd: 29.2

quality:
  mean_quality: 34
  tail_decay: 0.0015

tumour:
  purity: 0.004648
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0025_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 3.44
  family_size_sd: 2.04

chromosomes:
  - chr1

seed: 418560
