# varforge config: INDEL_ML3_TRAIN_VAF0173_1462 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0173_1462
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0173_1462
  read_length: 150
  coverage: 2376.3
  platform: illumina

fragment:
  model: normal
  mean: 251.9
  sd: 39.4

quality:
  mean_quality: 33
  tail_decay: 0.0038

tumour:
  purity: 0.034527
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0175_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 9.88
  family_size_sd: 5.16

chromosomes:
  - chr1

seed: 420196
