# varforge config: INDEL_ML3_TRAIN_VAF0027_1220 — VAF 0.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0027_1220
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0027_1220
  read_length: 150
  coverage: 10428.4
  platform: illumina

fragment:
  model: normal
  mean: 234.4
  sd: 46.2

quality:
  mean_quality: 37
  tail_decay: 0.0010

tumour:
  purity: 0.005369
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0025_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 2.53
  family_size_sd: 0.67

chromosomes:
  - chr1

seed: 411082
