# varforge config: INDEL_ML3_TRAIN_VAF0026_1045 — VAF 0.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0026_1045
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0026_1045
  read_length: 150
  coverage: 6636.0
  platform: illumina

fragment:
  model: normal
  mean: 158.4
  sd: 45.1

quality:
  mean_quality: 39
  tail_decay: 0.0032

tumour:
  purity: 0.005266
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0025_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.34
  family_size_sd: 0.69

chromosomes:
  - chr1

seed: 479255
