# varforge config: INDEL_ML3_TRAIN_VAF1413_1253 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1413_1253
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1413_1253
  read_length: 150
  coverage: 2599.9
  platform: illumina

fragment:
  model: normal
  mean: 260.3
  sd: 33.3

quality:
  mean_quality: 39
  tail_decay: 0.0018

tumour:
  purity: 0.282588
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 1.94
  family_size_sd: 0.66

chromosomes:
  - chr1

seed: 432280
