# varforge config: INDEL_ML3_TRAIN_VAF0037_0334 — VAF 0.3500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0037_0334
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0037_0334
  read_length: 150
  coverage: 696.6
  platform: illumina

fragment:
  model: normal
  mean: 173.1
  sd: 28.8

quality:
  mean_quality: 38
  tail_decay: 0.0015

tumour:
  purity: 0.007374
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 1.98
  family_size_sd: 1.07

chromosomes:
  - chr1

seed: 423095
