# varforge config: INDEL_ML3_TRAIN_VAF0194_0881 — VAF 2.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0194_0881
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0194_0881
  read_length: 150
  coverage: 571.6
  platform: illumina

fragment:
  model: normal
  mean: 171.9
  sd: 48.4

quality:
  mean_quality: 34
  tail_decay: 0.0026

tumour:
  purity: 0.038736
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0200_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 4.10
  family_size_sd: 2.29

chromosomes:
  - chr1

seed: 491435
