# varforge config: INDEL_ML3_TRAIN_VAF0045_1619 — VAF 0.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0045_1619
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0045_1619
  read_length: 150
  coverage: 3020.2
  platform: illumina

fragment:
  model: normal
  mean: 207.6
  sd: 17.8

quality:
  mean_quality: 35
  tail_decay: 0.0044

tumour:
  purity: 0.009099
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0050_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 8.08
  family_size_sd: 3.75

chromosomes:
  - chr1

seed: 498690
