# varforge config: INDEL_ML3_TRAIN_VAF0005_1527 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0005_1527
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0005_1527
  read_length: 150
  coverage: 8503.3
  platform: illumina

fragment:
  model: normal
  mean: 180.1
  sd: 16.2

quality:
  mean_quality: 33
  tail_decay: 0.0046

tumour:
  purity: 0.000942
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 3.09
  family_size_sd: 0.70

chromosomes:
  - chr1

seed: 445911
