# varforge config: INDEL_ML3_TRAIN_VAF1293_0748 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1293_0748
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1293_0748
  read_length: 150
  coverage: 2055.7
  platform: illumina

fragment:
  model: normal
  mean: 278.9
  sd: 45.3

quality:
  mean_quality: 31
  tail_decay: 0.0016

tumour:
  purity: 0.258539
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 8.86
  family_size_sd: 4.13

chromosomes:
  - chr1

seed: 458161
