# varforge config: INDEL_ML3_TRAIN_VAF0022_0127 — VAF 0.2000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0022_0127
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0022_0127
  read_length: 150
  coverage: 862.7
  platform: illumina

fragment:
  model: normal
  mean: 166.4
  sd: 30.1

quality:
  mean_quality: 40
  tail_decay: 0.0036

tumour:
  purity: 0.004414
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0020_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 8.94
  family_size_sd: 3.52

chromosomes:
  - chr1

seed: 449416
