# varforge config: INDEL_ML3_TRAIN_VAF0830_0015 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0830_0015
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0830_0015
  read_length: 150
  coverage: 2429.6
  platform: illumina

fragment:
  model: normal
  mean: 227.0
  sd: 19.1

quality:
  mean_quality: 33
  tail_decay: 0.0021

tumour:
  purity: 0.166043
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.34
  family_size_sd: 0.85

chromosomes:
  - chr1

seed: 495439
