# varforge config: INDEL_ML3_TRAIN_VAF0114_1343 — VAF 1.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0114_1343
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0114_1343
  read_length: 150
  coverage: 2643.3
  platform: illumina

fragment:
  model: normal
  mean: 187.6
  sd: 46.3

quality:
  mean_quality: 33
  tail_decay: 0.0018

tumour:
  purity: 0.022892
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 5.18
  family_size_sd: 1.73

chromosomes:
  - chr1

seed: 426966
