# varforge config: INDEL_ML3_TRAIN_VAF0108_0679 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0108_0679
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0108_0679
  read_length: 150
  coverage: 3233.4
  platform: illumina

fragment:
  model: normal
  mean: 222.1
  sd: 45.1

quality:
  mean_quality: 39
  tail_decay: 0.0019

tumour:
  purity: 0.021646
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 9.16
  family_size_sd: 4.92

chromosomes:
  - chr1

seed: 482437
