# varforge config: INDEL_ML3_TRAIN_VAF0008_0856 — VAF 0.1000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0008_0856
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0008_0856
  read_length: 150
  coverage: 767.5
  platform: illumina

fragment:
  model: normal
  mean: 279.3
  sd: 49.8

quality:
  mean_quality: 37
  tail_decay: 0.0027

tumour:
  purity: 0.001612
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 4.01
  family_size_sd: 1.35

chromosomes:
  - chr1

seed: 463706
