# varforge config: INDEL_ML3_TRAIN_VAF1236_0836 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1236_0836
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1236_0836
  read_length: 150
  coverage: 8650.4
  platform: illumina

fragment:
  model: normal
  mean: 142.4
  sd: 37.8

quality:
  mean_quality: 35
  tail_decay: 0.0044

tumour:
  purity: 0.247189
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 7.98
  family_size_sd: 2.05

chromosomes:
  - chr1

seed: 430785
