# varforge config: INDEL_ML3_TRAIN_VAF0007_1414 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0007_1414
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0007_1414
  read_length: 150
  coverage: 2530.0
  platform: illumina

fragment:
  model: normal
  mean: 210.4
  sd: 43.3

quality:
  mean_quality: 30
  tail_decay: 0.0049

tumour:
  purity: 0.001353
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 2.19
  family_size_sd: 0.84

chromosomes:
  - chr1

seed: 486148
