# varforge config: INDEL_ML3_TRAIN_VAF0151_1347 — VAF 1.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0151_1347
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0151_1347
  read_length: 150
  coverage: 15685.2
  platform: illumina

fragment:
  model: normal
  mean: 220.5
  sd: 42.1

quality:
  mean_quality: 37
  tail_decay: 0.0037

tumour:
  purity: 0.030266
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0150_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 6.00
  family_size_sd: 3.60

chromosomes:
  - chr1

seed: 419798
