# varforge config: INDEL_ML3_TRAIN_VAF1492_1346 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1492_1346
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1492_1346
  read_length: 150
  coverage: 17998.7
  platform: illumina

fragment:
  model: normal
  mean: 172.5
  sd: 15.4

quality:
  mean_quality: 39
  tail_decay: 0.0038

tumour:
  purity: 0.298430
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 1.54
  family_size_sd: 0.33

chromosomes:
  - chr1

seed: 449671
