# varforge config: INDEL_ML3_TRAIN_VAF0033_0941 — VAF 0.3500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0033_0941
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0033_0941
  read_length: 150
  coverage: 12041.6
  platform: illumina

fragment:
  model: normal
  mean: 240.2
  sd: 18.6

quality:
  mean_quality: 32
  tail_decay: 0.0020

tumour:
  purity: 0.006643
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 5.33
  family_size_sd: 2.52

chromosomes:
  - chr1

seed: 493179
