# varforge config: INDEL_ML3_TRAIN_VAF0392_1106 — VAF 4.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0392_1106
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0392_1106
  read_length: 150
  coverage: 13899.4
  platform: illumina

fragment:
  model: normal
  mean: 180.5
  sd: 29.6

quality:
  mean_quality: 34
  tail_decay: 0.0016

tumour:
  purity: 0.078378
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0400_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 5.57
  family_size_sd: 3.18

chromosomes:
  - chr1

seed: 492973
