# varforge config: INDEL_ML3_TRAIN_VAF0069_1812 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0069_1812
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0069_1812
  read_length: 150
  coverage: 1674.3
  platform: illumina

fragment:
  model: normal
  mean: 155.1
  sd: 29.9

quality:
  mean_quality: 31
  tail_decay: 0.0044

tumour:
  purity: 0.013783
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 3.52
  family_size_sd: 1.85

chromosomes:
  - chr1

seed: 454705
