# varforge config: INDEL_ML3_TRAIN_VAF0165_1781 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0165_1781
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0165_1781
  read_length: 150
  coverage: 934.5
  platform: illumina

fragment:
  model: normal
  mean: 238.6
  sd: 25.3

quality:
  mean_quality: 35
  tail_decay: 0.0027

tumour:
  purity: 0.032909
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 4.14
  family_size_sd: 1.07

chromosomes:
  - chr1

seed: 445938
