# varforge config: INDEL_ML3_TRAIN_VAF0624_0955 — VAF 6.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0624_0955
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0624_0955
  read_length: 150
  coverage: 9815.0
  platform: illumina

fragment:
  model: normal
  mean: 247.5
  sd: 46.8

quality:
  mean_quality: 36
  tail_decay: 0.0046

tumour:
  purity: 0.124853
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0600_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 9.97
  family_size_sd: 3.40

chromosomes:
  - chr1

seed: 408430
