# varforge config: INDEL_ML3_TRAIN_VAF0013_1580 — VAF 0.1500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0013_1580
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0013_1580
  read_length: 150
  coverage: 12773.9
  platform: illumina

fragment:
  model: normal
  mean: 249.4
  sd: 29.5

quality:
  mean_quality: 36
  tail_decay: 0.0049

tumour:
  purity: 0.002686
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 3.50
  family_size_sd: 2.07

chromosomes:
  - chr1

seed: 424862
