# varforge config: INDEL_ML3_TRAIN_VAF0044_0550 — VAF 0.4000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0044_0550
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0044_0550
  read_length: 150
  coverage: 667.4
  platform: illumina

fragment:
  model: normal
  mean: 264.9
  sd: 42.6

quality:
  mean_quality: 39
  tail_decay: 0.0018

tumour:
  purity: 0.008807
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0040_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 5.13
  family_size_sd: 2.78

chromosomes:
  - chr1

seed: 483042
