# varforge config: INDEL_ML3_TRAIN_VAF0259_1064 — VAF 2.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0259_1064
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0259_1064
  read_length: 150
  coverage: 2268.4
  platform: illumina

fragment:
  model: normal
  mean: 188.9
  sd: 36.7

quality:
  mean_quality: 33
  tail_decay: 0.0039

tumour:
  purity: 0.051874
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0250_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 2.16
  family_size_sd: 0.95

chromosomes:
  - chr1

seed: 455348
