# varforge config: INDEL_ML3_TRAIN_VAF0069_1865 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0069_1865
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0069_1865
  read_length: 150
  coverage: 554.9
  platform: illumina

fragment:
  model: normal
  mean: 278.1
  sd: 16.9

quality:
  mean_quality: 35
  tail_decay: 0.0017

tumour:
  purity: 0.013828
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0075_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 4.79
  family_size_sd: 1.19

chromosomes:
  - chr1

seed: 412943
