# varforge config: INDEL_ML3_TRAIN_VAF0916_1820 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0916_1820
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0916_1820
  read_length: 150
  coverage: 2017.0
  platform: illumina

fragment:
  model: normal
  mean: 231.8
  sd: 17.3

quality:
  mean_quality: 36
  tail_decay: 0.0033

tumour:
  purity: 0.183255
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 9.19
  family_size_sd: 5.11

chromosomes:
  - chr1

seed: 415778
