# varforge config: INDEL_ML3_TRAIN_VAF1278_0462 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1278_0462
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1278_0462
  read_length: 150
  coverage: 519.7
  platform: illumina

fragment:
  model: normal
  mean: 266.5
  sd: 30.1

quality:
  mean_quality: 39
  tail_decay: 0.0027

tumour:
  purity: 0.255641
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 1.71
  family_size_sd: 0.55

chromosomes:
  - chr1

seed: 487296
