# varforge config: INDEL_ML3_TRAIN_VAF0048_1770 — VAF 0.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0048_1770
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0048_1770
  read_length: 150
  coverage: 930.7
  platform: illumina

fragment:
  model: normal
  mean: 237.2
  sd: 17.1

quality:
  mean_quality: 33
  tail_decay: 0.0016

tumour:
  purity: 0.009626
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0050_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 5.12
  family_size_sd: 2.39

chromosomes:
  - chr1

seed: 491323
