# varforge config: INDEL_ML3_TRAIN_VAF0898_1517 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0898_1517
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0898_1517
  read_length: 150
  coverage: 6067.0
  platform: illumina

fragment:
  model: normal
  mean: 167.6
  sd: 23.5

quality:
  mean_quality: 30
  tail_decay: 0.0014

tumour:
  purity: 0.179608
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 2.37
  family_size_sd: 0.85

chromosomes:
  - chr1

seed: 441993
