# varforge config: INDEL_ML3_TRAIN_VAF0077_0502 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0077_0502
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0077_0502
  read_length: 150
  coverage: 1583.0
  platform: illumina

fragment:
  model: normal
  mean: 165.9
  sd: 43.9

quality:
  mean_quality: 30
  tail_decay: 0.0034

tumour:
  purity: 0.015385
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0075_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 7.03
  family_size_sd: 3.92

chromosomes:
  - chr1

seed: 419916
