# varforge config: INDEL_ML3_TRAIN_VAF0004_1009 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0004_1009
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0004_1009
  read_length: 150
  coverage: 2077.8
  platform: illumina

fragment:
  model: normal
  mean: 165.8
  sd: 34.8

quality:
  mean_quality: 34
  tail_decay: 0.0040

tumour:
  purity: 0.000718
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 5.66
  family_size_sd: 3.39

chromosomes:
  - chr1

seed: 448308
