# varforge config: INDEL_ML3_TRAIN_VAF0883_1510 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0883_1510
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0883_1510
  read_length: 150
  coverage: 726.0
  platform: illumina

fragment:
  model: normal
  mean: 206.1
  sd: 41.7

quality:
  mean_quality: 32
  tail_decay: 0.0018

tumour:
  purity: 0.176508
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0800_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 2.05
  family_size_sd: 0.43

chromosomes:
  - chr1

seed: 461199
