# varforge config: INDEL_ML3_TRAIN_VAF0069_0067 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0069_0067
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0069_0067
  read_length: 150
  coverage: 12209.6
  platform: illumina

fragment:
  model: normal
  mean: 251.1
  sd: 44.7

quality:
  mean_quality: 33
  tail_decay: 0.0044

tumour:
  purity: 0.013805
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0075_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 7.44
  family_size_sd: 4.40

chromosomes:
  - chr1

seed: 466891
