# varforge config: INDEL_ML3_TRAIN_VAF0057_1733 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0057_1733
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0057_1733
  read_length: 150
  coverage: 1682.1
  platform: illumina

fragment:
  model: normal
  mean: 150.2
  sd: 36.3

quality:
  mean_quality: 37
  tail_decay: 0.0034

tumour:
  purity: 0.011314
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0060_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 5.03
  family_size_sd: 1.12

chromosomes:
  - chr1

seed: 413944
