# varforge config: INDEL_ML3_TRAIN_VAF0006_1095 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0006_1095
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0006_1095
  read_length: 150
  coverage: 6869.8
  platform: illumina

fragment:
  model: normal
  mean: 262.2
  sd: 39.9

quality:
  mean_quality: 40
  tail_decay: 0.0050

tumour:
  purity: 0.001198
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 8.26
  family_size_sd: 1.97

chromosomes:
  - chr1

seed: 429185
