# varforge config: INDEL_ML3_TRAIN_VAF0104_0517 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0104_0517
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0104_0517
  read_length: 150
  coverage: 1322.3
  platform: illumina

fragment:
  model: normal
  mean: 197.0
  sd: 45.7

quality:
  mean_quality: 36
  tail_decay: 0.0026

tumour:
  purity: 0.020840
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0100_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 7.60
  family_size_sd: 4.48

chromosomes:
  - chr1

seed: 453895
