# varforge config: INDEL_ML3_TRAIN_VAF0056_0717 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0056_0717
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0056_0717
  read_length: 150
  coverage: 1039.7
  platform: illumina

fragment:
  model: normal
  mean: 216.4
  sd: 39.9

quality:
  mean_quality: 39
  tail_decay: 0.0027

tumour:
  purity: 0.011257
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0060_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 3.68
  family_size_sd: 1.77

chromosomes:
  - chr1

seed: 478696
