# varforge config: INDEL_ML3_TRAIN_VAF0531_1658 — VAF 5.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0531_1658
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0531_1658
  read_length: 150
  coverage: 12025.4
  platform: illumina

fragment:
  model: normal
  mean: 180.4
  sd: 35.3

quality:
  mean_quality: 32
  tail_decay: 0.0050

tumour:
  purity: 0.106184
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0500_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 2.27
  family_size_sd: 0.92

chromosomes:
  - chr1

seed: 464275
