# varforge config: INDEL_ML3_TRAIN_VAF0065_1423 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0065_1423
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0065_1423
  read_length: 150
  coverage: 1452.6
  platform: illumina

fragment:
  model: normal
  mean: 208.2
  sd: 33.1

quality:
  mean_quality: 34
  tail_decay: 0.0019

tumour:
  purity: 0.012982
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0060_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 4.29
  family_size_sd: 2.41

chromosomes:
  - chr1

seed: 486460
