# varforge config: INDEL_ML3_TRAIN_VAF0152_1744 — VAF 1.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0152_1744
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0152_1744
  read_length: 150
  coverage: 1656.3
  platform: illumina

fragment:
  model: normal
  mean: 209.1
  sd: 27.4

quality:
  mean_quality: 31
  tail_decay: 0.0015

tumour:
  purity: 0.030498
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0150_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 6.84
  family_size_sd: 3.92

chromosomes:
  - chr1

seed: 466248
