# varforge config: INDEL_ML3_TRAIN_VAF0632_1709 — VAF 6.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0632_1709
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0632_1709
  read_length: 150
  coverage: 2667.0
  platform: illumina

fragment:
  model: normal
  mean: 151.2
  sd: 27.3

quality:
  mean_quality: 34
  tail_decay: 0.0010

tumour:
  purity: 0.126381
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0600_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 8.27
  family_size_sd: 1.86

chromosomes:
  - chr1

seed: 414807
