# varforge config: INDEL_ML3_TRAIN_VAF1192_0290 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1192_0290
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1192_0290
  read_length: 150
  coverage: 3451.2
  platform: illumina

fragment:
  model: normal
  mean: 153.7
  sd: 19.4

quality:
  mean_quality: 35
  tail_decay: 0.0047

tumour:
  purity: 0.238334
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 3.84
  family_size_sd: 1.04

chromosomes:
  - chr1

seed: 437992
