# varforge config: INDEL_ML3_TRAIN_VAF0391_0273 — VAF 4.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0391_0273
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0391_0273
  read_length: 150
  coverage: 536.1
  platform: illumina

fragment:
  model: normal
  mean: 218.1
  sd: 48.1

quality:
  mean_quality: 36
  tail_decay: 0.0018

tumour:
  purity: 0.078266
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0400_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.29
  family_size_sd: 1.06

chromosomes:
  - chr1

seed: 441919
