# varforge config: INDEL_ML3_TRAIN_VAF0996_1189 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0996_1189
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0996_1189
  read_length: 150
  coverage: 5496.8
  platform: illumina

fragment:
  model: normal
  mean: 154.0
  sd: 26.6

quality:
  mean_quality: 30
  tail_decay: 0.0048

tumour:
  purity: 0.199125
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 4.49
  family_size_sd: 2.10

chromosomes:
  - chr1

seed: 464406
