# varforge config: INDEL_ML3_TRAIN_VAF1254_0490 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf1254_0490
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF1254_0490
  read_length: 150
  coverage: 608.5
  platform: illumina

fragment:
  model: normal
  mean: 201.2
  sd: 27.2

quality:
  mean_quality: 37
  tail_decay: 0.0043

tumour:
  purity: 0.250730
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 4.42
  family_size_sd: 1.08

chromosomes:
  - chr1

seed: 475591
