# varforge config: INDEL_ML3_TRAIN_VAF0708_0489 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0708_0489
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0708_0489
  read_length: 150
  coverage: 3378.0
  platform: illumina

fragment:
  model: normal
  mean: 194.2
  sd: 46.1

quality:
  mean_quality: 37
  tail_decay: 0.0025

tumour:
  purity: 0.141511
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 3.72
  family_size_sd: 1.78

chromosomes:
  - chr1

seed: 486453
