# varforge config: INDEL_ML3_TRAIN_VAF0023_1954 — VAF 0.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0023_1954
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0023_1954
  read_length: 150
  coverage: 5827.5
  platform: illumina

fragment:
  model: normal
  mean: 140.2
  sd: 19.5

quality:
  mean_quality: 31
  tail_decay: 0.0048

tumour:
  purity: 0.004655
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0025_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 3.25
  family_size_sd: 0.67

chromosomes:
  - chr1

seed: 484792
