# varforge config: INDEL_ML3_TRAIN_VAF0442_1854 — VAF 4.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0442_1854
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0442_1854
  read_length: 150
  coverage: 7588.2
  platform: illumina

fragment:
  model: normal
  mean: 227.2
  sd: 24.5

quality:
  mean_quality: 36
  tail_decay: 0.0024

tumour:
  purity: 0.088320
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0400_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 3.92
  family_size_sd: 1.22

chromosomes:
  - chr1

seed: 475162
