# varforge config: INDEL_ML3_TRAIN_VAF0032_0839 — VAF 0.3000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0032_0839
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0032_0839
  read_length: 150
  coverage: 942.7
  platform: illumina

fragment:
  model: normal
  mean: 142.6
  sd: 28.1

quality:
  mean_quality: 36
  tail_decay: 0.0037

tumour:
  purity: 0.006374
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0030_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 4.78
  family_size_sd: 1.09

chromosomes:
  - chr1

seed: 483401
