# varforge config: INDEL_ML3_TRAIN_VAF0186_1853 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0186_1853
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0186_1853
  read_length: 150
  coverage: 19835.9
  platform: illumina

fragment:
  model: normal
  mean: 223.8
  sd: 19.6

quality:
  mean_quality: 34
  tail_decay: 0.0039

tumour:
  purity: 0.037290
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.33
  family_size_sd: 1.73

chromosomes:
  - chr1

seed: 409631
