# varforge config: INDEL_ML3_TRAIN_VAF0007_1014 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0007_1014
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0007_1014
  read_length: 150
  coverage: 1780.6
  platform: illumina

fragment:
  model: normal
  mean: 153.8
  sd: 36.6

quality:
  mean_quality: 36
  tail_decay: 0.0037

tumour:
  purity: 0.001344
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 7.07
  family_size_sd: 2.24

chromosomes:
  - chr1

seed: 486307
