# varforge config: INDEL_ML3_TRAIN_VAF0012_1448 — VAF 0.1000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0012_1448
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0012_1448
  read_length: 150
  coverage: 5146.9
  platform: illumina

fragment:
  model: normal
  mean: 144.3
  sd: 44.2

quality:
  mean_quality: 35
  tail_decay: 0.0048

tumour:
  purity: 0.002308
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 4.40
  family_size_sd: 1.18

chromosomes:
  - chr1

seed: 434999
