# varforge config: INDEL_ML3_TRAIN_VAF0273_1199 — VAF 2.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0273_1199
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0273_1199
  read_length: 150
  coverage: 6415.4
  platform: illumina

fragment:
  model: normal
  mean: 235.6
  sd: 47.1

quality:
  mean_quality: 30
  tail_decay: 0.0032

tumour:
  purity: 0.054668
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0250_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 1.90
  family_size_sd: 0.43

chromosomes:
  - chr1

seed: 475861
