# varforge config: INDEL_ML3_TRAIN_VAF0467_1482 — VAF 5.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0467_1482
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0467_1482
  read_length: 150
  coverage: 4222.0
  platform: illumina

fragment:
  model: normal
  mean: 231.3
  sd: 28.5

quality:
  mean_quality: 39
  tail_decay: 0.0015

tumour:
  purity: 0.093443
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0500_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.89
  family_size_sd: 1.64

chromosomes:
  - chr1

seed: 401622
