# varforge config: INDEL_ML3_TRAIN_VAF0063_0304 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0063_0304
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0063_0304
  read_length: 150
  coverage: 1880.2
  platform: illumina

fragment:
  model: normal
  mean: 131.4
  sd: 42.2

quality:
  mean_quality: 34
  tail_decay: 0.0049

tumour:
  purity: 0.012699
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0060_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 4.13
  family_size_sd: 1.58

chromosomes:
  - chr1

seed: 464466
