# varforge config: INDEL_ML3_TRAIN_VAF0182_1650 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0182_1650
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0182_1650
  read_length: 150
  coverage: 2189.3
  platform: illumina

fragment:
  model: normal
  mean: 154.3
  sd: 18.6

quality:
  mean_quality: 32
  tail_decay: 0.0021

tumour:
  purity: 0.036404
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 3.47
  family_size_sd: 1.82

chromosomes:
  - chr1

seed: 479394
