# varforge config: INDEL_ML3_TRAIN_VAF0089_1934 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0089_1934
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0089_1934
  read_length: 150
  coverage: 13262.3
  platform: illumina

fragment:
  model: normal
  mean: 142.8
  sd: 19.9

quality:
  mean_quality: 36
  tail_decay: 0.0013

tumour:
  purity: 0.017716
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 7.49
  family_size_sd: 3.93

chromosomes:
  - chr1

seed: 436630
