# varforge config: INDEL_ML3_TRAIN_VAF0163_0442 — VAF 1.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_indel_ml3_train_vaf0163_0442
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INDEL_ML3_TRAIN_VAF0163_0442
  read_length: 150
  coverage: 1410.9
  platform: illumina

fragment:
  model: normal
  mean: 213.5
  sd: 22.0

quality:
  mean_quality: 39
  tail_decay: 0.0019

tumour:
  purity: 0.032534
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_indels_vaf0175_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 4.24
  family_size_sd: 1.23

chromosomes:
  - chr1

seed: 462782
