# varforge config: INS_ML3_TRAIN_VAF1001_1407 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf1001_1407
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF1001_1407
  read_length: 150
  coverage: 5836.1
  platform: illumina

fragment:
  model: normal
  mean: 202.7
  sd: 22.1

quality:
  mean_quality: 33
  tail_decay: 0.0019

tumour:
  purity: 0.200104
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 1.87
  family_size_sd: 0.50

chromosomes:
  - chr1

seed: 497920
