# varforge config: INS_ML3_TRAIN_VAF0399_0558 — VAF 4.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0399_0558
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0399_0558
  read_length: 150
  coverage: 2170.2
  platform: illumina

fragment:
  model: normal
  mean: 238.9
  sd: 33.1

quality:
  mean_quality: 33
  tail_decay: 0.0014

tumour:
  purity: 0.079821
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0400_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 5.78
  family_size_sd: 2.42

chromosomes:
  - chr1

seed: 480602
