# varforge config: INS_ML3_TRAIN_VAF0204_0589 — VAF 2.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0204_0589
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0204_0589
  read_length: 150
  coverage: 1723.3
  platform: illumina

fragment:
  model: normal
  mean: 229.1
  sd: 17.0

quality:
  mean_quality: 34
  tail_decay: 0.0016

tumour:
  purity: 0.040762
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0200_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 4.01
  family_size_sd: 2.01

chromosomes:
  - chr1

seed: 458870
