# varforge config: INS_ML3_TRAIN_VAF1112_0824 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf1112_0824
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF1112_0824
  read_length: 150
  coverage: 6753.5
  platform: illumina

fragment:
  model: normal
  mean: 183.0
  sd: 29.9

quality:
  mean_quality: 31
  tail_decay: 0.0026

tumour:
  purity: 0.222431
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.74
  family_size_sd: 0.85

chromosomes:
  - chr1

seed: 492703
