# varforge config: INS_ML3_TRAIN_VAF0461_0284 — VAF 5.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0461_0284
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0461_0284
  read_length: 150
  coverage: 6412.7
  platform: illumina

fragment:
  model: normal
  mean: 217.5
  sd: 31.7

quality:
  mean_quality: 31
  tail_decay: 0.0030

tumour:
  purity: 0.092204
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0500_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 5.38
  family_size_sd: 1.65

chromosomes:
  - chr1

seed: 417084
