# varforge config: INS_ML3_TRAIN_VAF0405_0970 — VAF 4.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0405_0970
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0405_0970
  read_length: 150
  coverage: 17593.9
  platform: illumina

fragment:
  model: normal
  mean: 209.0
  sd: 49.7

quality:
  mean_quality: 31
  tail_decay: 0.0029

tumour:
  purity: 0.080904
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0400_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 4.61
  family_size_sd: 1.13

chromosomes:
  - chr1

seed: 413675
