# varforge config: INS_ML3_TRAIN_VAF0057_1411 — VAF 0.6000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0057_1411
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0057_1411
  read_length: 150
  coverage: 565.4
  platform: illumina

fragment:
  model: normal
  mean: 263.0
  sd: 23.8

quality:
  mean_quality: 35
  tail_decay: 0.0027

tumour:
  purity: 0.011476
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0060_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 8.96
  family_size_sd: 4.19

chromosomes:
  - chr1

seed: 479482
