# varforge config: INS_ML3_TRAIN_VAF0023_1843 — VAF 0.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0023_1843
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0023_1843
  read_length: 150
  coverage: 5221.3
  platform: illumina

fragment:
  model: normal
  mean: 260.5
  sd: 37.0

quality:
  mean_quality: 37
  tail_decay: 0.0035

tumour:
  purity: 0.004505
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0025_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 6.82
  family_size_sd: 2.22

chromosomes:
  - chr1

seed: 411505
