# varforge config: INS_ML3_TRAIN_VAF0079_1689 — VAF 0.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0079_1689
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0079_1689
  read_length: 150
  coverage: 7695.9
  platform: illumina

fragment:
  model: normal
  mean: 189.3
  sd: 46.9

quality:
  mean_quality: 32
  tail_decay: 0.0021

tumour:
  purity: 0.015830
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0075_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 7.98
  family_size_sd: 2.85

chromosomes:
  - chr1

seed: 464474
