# varforge config: INS_ML3_TRAIN_VAF1448_1272 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf1448_1272
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF1448_1272
  read_length: 150
  coverage: 2643.6
  platform: illumina

fragment:
  model: normal
  mean: 151.5
  sd: 35.1

quality:
  mean_quality: 32
  tail_decay: 0.0026

tumour:
  purity: 0.289642
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 3.95
  family_size_sd: 1.47

chromosomes:
  - chr1

seed: 418070
