# varforge config: INS_ML3_TRAIN_VAF0008_0038 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0008_0038
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0008_0038
  read_length: 150
  coverage: 1832.1
  platform: illumina

fragment:
  model: normal
  mean: 205.3
  sd: 31.3

quality:
  mean_quality: 30
  tail_decay: 0.0039

tumour:
  purity: 0.001601
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 5.47
  family_size_sd: 2.01

chromosomes:
  - chr1

seed: 442599
