# varforge config: INS_ML3_TRAIN_VAF0571_0917 — VAF 6.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0571_0917
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0571_0917
  read_length: 150
  coverage: 7236.4
  platform: illumina

fragment:
  model: normal
  mean: 138.2
  sd: 28.3

quality:
  mean_quality: 37
  tail_decay: 0.0043

tumour:
  purity: 0.114214
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0600_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 1.57
  family_size_sd: 0.40

chromosomes:
  - chr1

seed: 440793
