# varforge config: INS_ML3_TRAIN_VAF0551_0883 — VAF 6.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0551_0883
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0551_0883
  read_length: 150
  coverage: 9134.7
  platform: illumina

fragment:
  model: normal
  mean: 141.7
  sd: 44.9

quality:
  mean_quality: 34
  tail_decay: 0.0035

tumour:
  purity: 0.110260
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0600_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 3.48
  family_size_sd: 1.63

chromosomes:
  - chr1

seed: 430764
