# varforge config: INS_ML3_TRAIN_VAF0329_0123 — VAF 3.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0329_0123
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0329_0123
  read_length: 150
  coverage: 16683.2
  platform: illumina

fragment:
  model: normal
  mean: 204.1
  sd: 27.9

quality:
  mean_quality: 32
  tail_decay: 0.0016

tumour:
  purity: 0.065705
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0350_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 5.67
  family_size_sd: 2.77

chromosomes:
  - chr1

seed: 481960
