# varforge config: INS_ML3_TRAIN_VAF0019_1376 — VAF 0.2000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0019_1376
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0019_1376
  read_length: 150
  coverage: 620.2
  platform: illumina

fragment:
  model: normal
  mean: 212.8
  sd: 29.4

quality:
  mean_quality: 31
  tail_decay: 0.0035

tumour:
  purity: 0.003702
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0020_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 8.00
  family_size_sd: 4.66

chromosomes:
  - chr1

seed: 453509
