# varforge config: INS_ML3_TRAIN_VAF0125_1480 — VAF 1.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0125_1480
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0125_1480
  read_length: 150
  coverage: 10141.4
  platform: illumina

fragment:
  model: normal
  mean: 204.6
  sd: 41.0

quality:
  mean_quality: 37
  tail_decay: 0.0028

tumour:
  purity: 0.024921
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 2.27
  family_size_sd: 0.88

chromosomes:
  - chr1

seed: 423869
