# varforge config: INS_ML3_TRAIN_VAF0058_1490 — VAF 0.6000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0058_1490
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0058_1490
  read_length: 150
  coverage: 13614.3
  platform: illumina

fragment:
  model: normal
  mean: 152.3
  sd: 32.6

quality:
  mean_quality: 35
  tail_decay: 0.0026

tumour:
  purity: 0.011584
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0060_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 4.97
  family_size_sd: 1.71

chromosomes:
  - chr1

seed: 442873
