# varforge config: INS_ML3_TRAIN_VAF0246_0742 — VAF 2.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0246_0742
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0246_0742
  read_length: 150
  coverage: 10921.2
  platform: illumina

fragment:
  model: normal
  mean: 211.5
  sd: 42.3

quality:
  mean_quality: 37
  tail_decay: 0.0021

tumour:
  purity: 0.049296
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0250_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 9.37
  family_size_sd: 2.59

chromosomes:
  - chr1

seed: 440202
