# varforge config: INS_ML3_TRAIN_VAF0120_0571 — VAF 1.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0120_0571
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0120_0571
  read_length: 150
  coverage: 8139.8
  platform: illumina

fragment:
  model: normal
  mean: 211.6
  sd: 18.1

quality:
  mean_quality: 34
  tail_decay: 0.0048

tumour:
  purity: 0.024050
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0125_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.97
  family_size_sd: 1.44

chromosomes:
  - chr1

seed: 422757
