# varforge config: INS_ML3_TRAIN_VAF0022_0260 — VAF 0.2000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0022_0260
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0022_0260
  read_length: 150
  coverage: 3388.7
  platform: illumina

fragment:
  model: normal
  mean: 248.4
  sd: 15.1

quality:
  mean_quality: 36
  tail_decay: 0.0016

tumour:
  purity: 0.004338
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0020_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 8.21
  family_size_sd: 2.48

chromosomes:
  - chr1

seed: 406545
