# varforge config: INS_ML3_TRAIN_VAF0069_0793 — VAF 0.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0069_0793
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0069_0793
  read_length: 150
  coverage: 9551.0
  platform: illumina

fragment:
  model: normal
  mean: 215.3
  sd: 21.7

quality:
  mean_quality: 34
  tail_decay: 0.0050

tumour:
  purity: 0.013770
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 7.52
  family_size_sd: 3.71

chromosomes:
  - chr1

seed: 408902
