# varforge config: INS_ML3_TRAIN_VAF0003_1504 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0003_1504
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0003_1504
  read_length: 150
  coverage: 2013.5
  platform: illumina

fragment:
  model: normal
  mean: 148.7
  sd: 29.1

quality:
  mean_quality: 31
  tail_decay: 0.0039

tumour:
  purity: 0.000634
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.17
  family_size_sd: 1.88

chromosomes:
  - chr1

seed: 458087
