# varforge config: INS_ML3_TRAIN_VAF0283_1517 — VAF 3.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0283_1517
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0283_1517
  read_length: 150
  coverage: 18362.6
  platform: illumina

fragment:
  model: normal
  mean: 270.9
  sd: 28.8

quality:
  mean_quality: 33
  tail_decay: 0.0036

tumour:
  purity: 0.056557
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0300_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 3.13
  family_size_sd: 0.65

chromosomes:
  - chr1

seed: 447341
