# varforge config: INS_ML3_TRAIN_VAF0018_1326 — VAF 0.2000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0018_1326
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0018_1326
  read_length: 150
  coverage: 599.3
  platform: illumina

fragment:
  model: normal
  mean: 270.9
  sd: 32.9

quality:
  mean_quality: 38
  tail_decay: 0.0014

tumour:
  purity: 0.003516
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0020_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 2.24
  family_size_sd: 0.88

chromosomes:
  - chr1

seed: 421823
