# varforge config: INS_ML3_TRAIN_VAF0310_0119 — VAF 3.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0310_0119
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0310_0119
  read_length: 150
  coverage: 2139.0
  platform: illumina

fragment:
  model: normal
  mean: 278.7
  sd: 29.0

quality:
  mean_quality: 33
  tail_decay: 0.0035

tumour:
  purity: 0.062075
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0300_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 5.60
  family_size_sd: 1.14

chromosomes:
  - chr1

seed: 475673
