# varforge config: INS_ML3_TRAIN_VAF0027_1879 — VAF 0.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0027_1879
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0027_1879
  read_length: 150
  coverage: 4347.9
  platform: illumina

fragment:
  model: normal
  mean: 279.9
  sd: 18.1

quality:
  mean_quality: 34
  tail_decay: 0.0050

tumour:
  purity: 0.005414
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0025_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.35
  family_size_sd: 1.69

chromosomes:
  - chr1

seed: 484644
