# varforge config: INS_ML3_TRAIN_VAF0245_1076 — VAF 2.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0245_1076
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0245_1076
  read_length: 150
  coverage: 14246.1
  platform: illumina

fragment:
  model: normal
  mean: 200.2
  sd: 41.3

quality:
  mean_quality: 39
  tail_decay: 0.0043

tumour:
  purity: 0.048995
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0250_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 6.50
  family_size_sd: 2.65

chromosomes:
  - chr1

seed: 438857
