# varforge config: INS_ML3_TRAIN_VAF0144_1215 — VAF 1.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0144_1215
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0144_1215
  read_length: 150
  coverage: 9281.4
  platform: illumina

fragment:
  model: normal
  mean: 174.8
  sd: 43.5

quality:
  mean_quality: 34
  tail_decay: 0.0041

tumour:
  purity: 0.028841
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0150_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 8.49
  family_size_sd: 1.92

chromosomes:
  - chr1

seed: 448837
