# varforge config: INS_ML3_TRAIN_VAF0029_1359 — VAF 0.3000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0029_1359
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0029_1359
  read_length: 150
  coverage: 5472.6
  platform: illumina

fragment:
  model: normal
  mean: 205.4
  sd: 31.0

quality:
  mean_quality: 39
  tail_decay: 0.0032

tumour:
  purity: 0.005784
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0030_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 3.24
  family_size_sd: 0.76

chromosomes:
  - chr1

seed: 462241
