# varforge config: INS_ML3_TRAIN_VAF1387_0973 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf1387_0973
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF1387_0973
  read_length: 150
  coverage: 5993.7
  platform: illumina

fragment:
  model: normal
  mean: 161.7
  sd: 45.1

quality:
  mean_quality: 35
  tail_decay: 0.0025

tumour:
  purity: 0.277438
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 3.90
  family_size_sd: 1.34

chromosomes:
  - chr1

seed: 445901
