# varforge config: INS_ML3_TRAIN_VAF0074_1303 — VAF 0.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0074_1303
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0074_1303
  read_length: 150
  coverage: 18572.9
  platform: illumina

fragment:
  model: normal
  mean: 259.2
  sd: 22.3

quality:
  mean_quality: 40
  tail_decay: 0.0042

tumour:
  purity: 0.014815
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 4.32
  family_size_sd: 1.92

chromosomes:
  - chr1

seed: 418391
