# varforge config: INS_ML3_TRAIN_VAF1377_0374 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf1377_0374
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF1377_0374
  read_length: 150
  coverage: 4203.0
  platform: illumina

fragment:
  model: normal
  mean: 228.7
  sd: 31.9

quality:
  mean_quality: 38
  tail_decay: 0.0037

tumour:
  purity: 0.275436
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 6.59
  family_size_sd: 2.82

chromosomes:
  - chr1

seed: 442412
