# varforge config: INS_ML3_TRAIN_VAF0054_1943 — VAF 0.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0054_1943
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0054_1943
  read_length: 150
  coverage: 799.5
  platform: illumina

fragment:
  model: normal
  mean: 166.5
  sd: 47.5

quality:
  mean_quality: 32
  tail_decay: 0.0012

tumour:
  purity: 0.010889
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0050_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 5.64
  family_size_sd: 1.95

chromosomes:
  - chr1

seed: 487648
