# varforge config: INS_ML3_TRAIN_VAF1074_1442 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf1074_1442
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF1074_1442
  read_length: 150
  coverage: 3050.7
  platform: illumina

fragment:
  model: normal
  mean: 229.5
  sd: 37.3

quality:
  mean_quality: 40
  tail_decay: 0.0017

tumour:
  purity: 0.214712
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 7.70
  family_size_sd: 1.55

chromosomes:
  - chr1

seed: 451325
