# varforge config: INS_ML3_TRAIN_VAF0008_1431 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0008_1431
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0008_1431
  read_length: 150
  coverage: 959.4
  platform: illumina

fragment:
  model: normal
  mean: 268.5
  sd: 18.7

quality:
  mean_quality: 36
  tail_decay: 0.0027

tumour:
  purity: 0.001560
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 6.25
  family_size_sd: 2.52

chromosomes:
  - chr1

seed: 488626
