# varforge config: INS_ML3_TRAIN_VAF0071_1935 — VAF 0.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0071_1935
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0071_1935
  read_length: 150
  coverage: 1900.4
  platform: illumina

fragment:
  model: normal
  mean: 185.2
  sd: 29.1

quality:
  mean_quality: 39
  tail_decay: 0.0025

tumour:
  purity: 0.014160
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0075_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 1.75
  family_size_sd: 0.40

chromosomes:
  - chr1

seed: 405580
