# varforge config: INS_ML3_TRAIN_VAF0071_1717 — VAF 0.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0071_1717
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0071_1717
  read_length: 150
  coverage: 5901.8
  platform: illumina

fragment:
  model: normal
  mean: 147.1
  sd: 48.3

quality:
  mean_quality: 40
  tail_decay: 0.0017

tumour:
  purity: 0.014269
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 3.84
  family_size_sd: 1.24

chromosomes:
  - chr1

seed: 460845
