# varforge config: INS_ML3_TRAIN_VAF0361_0540 — VAF 3.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0361_0540
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0361_0540
  read_length: 150
  coverage: 5159.0
  platform: illumina

fragment:
  model: normal
  mean: 159.7
  sd: 21.3

quality:
  mean_quality: 32
  tail_decay: 0.0042

tumour:
  purity: 0.072258
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0350_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 7.63
  family_size_sd: 2.98

chromosomes:
  - chr1

seed: 453117
