# varforge config: INS_ML3_TRAIN_VAF0006_0476 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0006_0476
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0006_0476
  read_length: 150
  coverage: 2793.1
  platform: illumina

fragment:
  model: normal
  mean: 199.7
  sd: 27.5

quality:
  mean_quality: 30
  tail_decay: 0.0039

tumour:
  purity: 0.001241
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 7.62
  family_size_sd: 4.17

chromosomes:
  - chr1

seed: 438569
