# varforge config: INS_ML3_TRAIN_VAF0095_1233 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0095_1233
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0095_1233
  read_length: 150
  coverage: 1325.1
  platform: illumina

fragment:
  model: normal
  mean: 174.6
  sd: 47.6

quality:
  mean_quality: 33
  tail_decay: 0.0040

tumour:
  purity: 0.019056
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0100_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 5.45
  family_size_sd: 1.53

chromosomes:
  - chr1

seed: 478963
