# varforge config: INS_ML3_TRAIN_VAF0004_1513 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0004_1513
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0004_1513
  read_length: 150
  coverage: 2987.8
  platform: illumina

fragment:
  model: normal
  mean: 165.4
  sd: 39.5

quality:
  mean_quality: 36
  tail_decay: 0.0031

tumour:
  purity: 0.000775
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 8.67
  family_size_sd: 2.13

chromosomes:
  - chr1

seed: 440769
