# varforge config: INS_ML3_TRAIN_VAF0081_1013 — VAF 0.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0081_1013
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0081_1013
  read_length: 150
  coverage: 3205.0
  platform: illumina

fragment:
  model: normal
  mean: 189.1
  sd: 39.9

quality:
  mean_quality: 37
  tail_decay: 0.0014

tumour:
  purity: 0.016117
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 5.16
  family_size_sd: 2.64

chromosomes:
  - chr1

seed: 436504
