# varforge config: INS_ML3_TRAIN_VAF1109_1408 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf1109_1408
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF1109_1408
  read_length: 150
  coverage: 14873.2
  platform: illumina

fragment:
  model: normal
  mean: 190.0
  sd: 35.4

quality:
  mean_quality: 33
  tail_decay: 0.0029

tumour:
  purity: 0.221717
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 9.77
  family_size_sd: 5.11

chromosomes:
  - chr1

seed: 489978
