# varforge config: INS_ML3_TRAIN_VAF0034_0514 — VAF 0.3500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0034_0514
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0034_0514
  read_length: 150
  coverage: 12453.2
  platform: illumina

fragment:
  model: normal
  mean: 169.2
  sd: 45.8

quality:
  mean_quality: 33
  tail_decay: 0.0015

tumour:
  purity: 0.006883
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0035_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 2.24
  family_size_sd: 1.19

chromosomes:
  - chr1

seed: 455595
