# varforge config: INS_ML3_TRAIN_VAF0019_0066 — VAF 0.2000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0019_0066
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0019_0066
  read_length: 150
  coverage: 3718.3
  platform: illumina

fragment:
  model: normal
  mean: 247.6
  sd: 44.6

quality:
  mean_quality: 33
  tail_decay: 0.0020

tumour:
  purity: 0.003797
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0020_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.38
  family_size_sd: 1.39

chromosomes:
  - chr1

seed: 457988
