# varforge config: INS_ML3_TRAIN_VAF0025_1368 — VAF 0.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0025_1368
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0025_1368
  read_length: 150
  coverage: 4407.1
  platform: illumina

fragment:
  model: normal
  mean: 176.6
  sd: 19.3

quality:
  mean_quality: 34
  tail_decay: 0.0011

tumour:
  purity: 0.005096
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0025_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 3.98
  family_size_sd: 1.96

chromosomes:
  - chr1

seed: 418860
