# varforge config: INS_ML3_TRAIN_VAF0105_1867 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_ins_ml3_train_vaf0105_1867
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INS_ML3_TRAIN_VAF0105_1867
  read_length: 150
  coverage: 1264.4
  platform: illumina

fragment:
  model: normal
  mean: 177.9
  sd: 41.8

quality:
  mean_quality: 36
  tail_decay: 0.0049

tumour:
  purity: 0.021036
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_ins_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.05
  family_size_sd: 0.92

chromosomes:
  - chr1

seed: 464634
