# varforge config: INVDEL_ML3_TRAIN_VAF0006_1342 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0006_1342
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0006_1342
  read_length: 150
  coverage: 550.4
  platform: illumina

fragment:
  model: normal
  mean: 252.6
  sd: 30.1

quality:
  mean_quality: 35
  tail_decay: 0.0035

tumour:
  purity: 0.001230
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 1.74
  family_size_sd: 0.53

chromosomes:
  - chr1

seed: 410827
