# varforge config: INVDEL_ML3_TRAIN_VAF1062_1715 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf1062_1715
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF1062_1715
  read_length: 150
  coverage: 1032.1
  platform: illumina

fragment:
  model: normal
  mean: 208.6
  sd: 33.8

quality:
  mean_quality: 32
  tail_decay: 0.0048

tumour:
  purity: 0.212434
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 4.35
  family_size_sd: 1.10

chromosomes:
  - chr1

seed: 498212
