# varforge config: INVDEL_ML3_TRAIN_VAF0278_0384 — VAF 3.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0278_0384
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0278_0384
  read_length: 150
  coverage: 7268.3
  platform: illumina

fragment:
  model: normal
  mean: 222.3
  sd: 49.7

quality:
  mean_quality: 33
  tail_decay: 0.0033

tumour:
  purity: 0.055547
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0300_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 5.11
  family_size_sd: 2.13

chromosomes:
  - chr1

seed: 453859
