# varforge config: INVDEL_ML3_TRAIN_VAF0006_0536 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0006_0536
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0006_0536
  read_length: 150
  coverage: 19544.1
  platform: illumina

fragment:
  model: normal
  mean: 157.3
  sd: 28.2

quality:
  mean_quality: 31
  tail_decay: 0.0042

tumour:
  purity: 0.001206
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 2.00
  family_size_sd: 0.49

chromosomes:
  - chr1

seed: 428228
