# varforge config: INVDEL_ML3_TRAIN_VAF0187_0835 — VAF 1.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0187_0835
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0187_0835
  read_length: 150
  coverage: 5776.1
  platform: illumina

fragment:
  model: normal
  mean: 239.5
  sd: 38.4

quality:
  mean_quality: 35
  tail_decay: 0.0010

tumour:
  purity: 0.037322
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0175_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 7.13
  family_size_sd: 2.09

chromosomes:
  - chr1

seed: 451099
