# varforge config: INVDEL_ML3_TRAIN_VAF0538_0131 — VAF 5.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0538_0131
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0538_0131
  read_length: 150
  coverage: 1083.1
  platform: illumina

fragment:
  model: normal
  mean: 145.4
  sd: 35.3

quality:
  mean_quality: 36
  tail_decay: 0.0028

tumour:
  purity: 0.107698
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0500_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.15
  family_size_sd: 1.03

chromosomes:
  - chr1

seed: 408952
