# varforge config: INVDEL_ML3_TRAIN_VAF0036_1893 — VAF 0.3500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0036_1893
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0036_1893
  read_length: 150
  coverage: 4805.2
  platform: illumina

fragment:
  model: normal
  mean: 205.5
  sd: 28.1

quality:
  mean_quality: 38
  tail_decay: 0.0013

tumour:
  purity: 0.007168
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 4.97
  family_size_sd: 1.59

chromosomes:
  - chr1

seed: 482512
