# varforge config: INVDEL_ML3_TRAIN_VAF0029_0853 — VAF 0.3000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0029_0853
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0029_0853
  read_length: 150
  coverage: 5161.9
  platform: illumina

fragment:
  model: normal
  mean: 153.0
  sd: 36.6

quality:
  mean_quality: 32
  tail_decay: 0.0036

tumour:
  purity: 0.005777
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0030_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 2.90
  family_size_sd: 0.95

chromosomes:
  - chr1

seed: 488859
