# varforge config: INVDEL_ML3_TRAIN_VAF0015_1250 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0015_1250
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0015_1250
  read_length: 150
  coverage: 14781.3
  platform: illumina

fragment:
  model: normal
  mean: 182.6
  sd: 47.0

quality:
  mean_quality: 33
  tail_decay: 0.0019

tumour:
  purity: 0.003076
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 4.17
  family_size_sd: 1.17

chromosomes:
  - chr1

seed: 436114
