# varforge config: INVDEL_ML3_TRAIN_VAF0162_0825 — VAF 1.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0162_0825
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0162_0825
  read_length: 150
  coverage: 15173.7
  platform: illumina

fragment:
  model: normal
  mean: 202.8
  sd: 22.7

quality:
  mean_quality: 31
  tail_decay: 0.0020

tumour:
  purity: 0.032309
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0150_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 6.67
  family_size_sd: 2.28

chromosomes:
  - chr1

seed: 446529
