# varforge config: INVDEL_ML3_TRAIN_VAF0019_1268 — VAF 0.2000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0019_1268
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0019_1268
  read_length: 150
  coverage: 565.0
  platform: illumina

fragment:
  model: normal
  mean: 269.9
  sd: 22.6

quality:
  mean_quality: 39
  tail_decay: 0.0049

tumour:
  purity: 0.003761
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0020_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 7.32
  family_size_sd: 3.90

chromosomes:
  - chr1

seed: 453316
