# varforge config: INVDEL_ML3_TRAIN_VAF0309_0523 — VAF 3.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0309_0523
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0309_0523
  read_length: 150
  coverage: 2708.9
  platform: illumina

fragment:
  model: normal
  mean: 274.5
  sd: 44.5

quality:
  mean_quality: 37
  tail_decay: 0.0034

tumour:
  purity: 0.061874
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0300_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 3.70
  family_size_sd: 1.92

chromosomes:
  - chr1

seed: 420628
