# varforge config: INVDEL_ML3_TRAIN_VAF0409_1863 — VAF 4.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0409_1863
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0409_1863
  read_length: 150
  coverage: 4324.3
  platform: illumina

fragment:
  model: normal
  mean: 248.9
  sd: 32.9

quality:
  mean_quality: 40
  tail_decay: 0.0021

tumour:
  purity: 0.081783
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0400_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 4.52
  family_size_sd: 2.52

chromosomes:
  - chr1

seed: 447491
