# varforge config: INVDEL_ML3_TRAIN_VAF0276_1422 — VAF 3.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0276_1422
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0276_1422
  read_length: 150
  coverage: 935.5
  platform: illumina

fragment:
  model: normal
  mean: 154.8
  sd: 25.5

quality:
  mean_quality: 31
  tail_decay: 0.0031

tumour:
  purity: 0.055110
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0300_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 6.04
  family_size_sd: 2.25

chromosomes:
  - chr1

seed: 424118
