# varforge config: INVDEL_ML3_TRAIN_VAF0010_1275 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0010_1275
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0010_1275
  read_length: 150
  coverage: 4540.0
  platform: illumina

fragment:
  model: normal
  mean: 184.9
  sd: 15.4

quality:
  mean_quality: 36
  tail_decay: 0.0010

tumour:
  purity: 0.001970
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 1.82
  family_size_sd: 1.02

chromosomes:
  - chr1

seed: 420744
