# varforge config: INVDEL_ML3_TRAIN_VAF0015_1392 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0015_1392
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0015_1392
  read_length: 150
  coverage: 4754.4
  platform: illumina

fragment:
  model: normal
  mean: 132.3
  sd: 27.6

quality:
  mean_quality: 36
  tail_decay: 0.0016

tumour:
  purity: 0.002911
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 4.54
  family_size_sd: 1.86

chromosomes:
  - chr1

seed: 423820
