# varforge config: INVDEL_ML3_TRAIN_VAF0613_0898 — VAF 6.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0613_0898
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0613_0898
  read_length: 150
  coverage: 652.7
  platform: illumina

fragment:
  model: normal
  mean: 154.9
  sd: 42.3

quality:
  mean_quality: 37
  tail_decay: 0.0027

tumour:
  purity: 0.122578
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0600_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 8.16
  family_size_sd: 1.68

chromosomes:
  - chr1

seed: 448446
