# varforge config: INVDEL_ML3_TRAIN_VAF0015_0424 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0015_0424
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0015_0424
  read_length: 150
  coverage: 2311.5
  platform: illumina

fragment:
  model: normal
  mean: 148.0
  sd: 47.5

quality:
  mean_quality: 40
  tail_decay: 0.0023

tumour:
  purity: 0.002999
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 3.93
  family_size_sd: 1.05

chromosomes:
  - chr1

seed: 490735
