# varforge config: INVDEL_ML3_TRAIN_VAF0100_0044 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0100_0044
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0100_0044
  read_length: 150
  coverage: 563.4
  platform: illumina

fragment:
  model: normal
  mean: 234.4
  sd: 27.1

quality:
  mean_quality: 33
  tail_decay: 0.0031

tumour:
  purity: 0.019992
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0100_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 8.27
  family_size_sd: 2.93

chromosomes:
  - chr1

seed: 470587
