# varforge config: INVDEL_ML3_TRAIN_VAF0092_0338 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0092_0338
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0092_0338
  read_length: 150
  coverage: 2947.7
  platform: illumina

fragment:
  model: normal
  mean: 269.7
  sd: 28.1

quality:
  mean_quality: 30
  tail_decay: 0.0030

tumour:
  purity: 0.018494
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0100_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 8.35
  family_size_sd: 3.82

chromosomes:
  - chr1

seed: 426718
