# varforge config: INVDEL_ML3_TRAIN_VAF0033_0039 — VAF 0.3500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0033_0039
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0033_0039
  read_length: 150
  coverage: 8732.6
  platform: illumina

fragment:
  model: normal
  mean: 130.2
  sd: 43.8

quality:
  mean_quality: 37
  tail_decay: 0.0034

tumour:
  purity: 0.006593
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 5.43
  family_size_sd: 2.68

chromosomes:
  - chr1

seed: 477271
