# varforge config: INVDEL_ML3_TRAIN_VAF0102_0328 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0102_0328
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0102_0328
  read_length: 150
  coverage: 2658.4
  platform: illumina

fragment:
  model: normal
  mean: 177.4
  sd: 21.5

quality:
  mean_quality: 38
  tail_decay: 0.0025

tumour:
  purity: 0.020488
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0100_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 8.43
  family_size_sd: 3.63

chromosomes:
  - chr1

seed: 498654
