# varforge config: INVDEL_ML3_TRAIN_VAF0107_0500 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0107_0500
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0107_0500
  read_length: 150
  coverage: 9705.8
  platform: illumina

fragment:
  model: normal
  mean: 232.0
  sd: 45.8

quality:
  mean_quality: 31
  tail_decay: 0.0033

tumour:
  purity: 0.021482
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 1.60
  family_size_sd: 0.83

chromosomes:
  - chr1

seed: 418051
