# varforge config: INVDEL_ML3_TRAIN_VAF1486_1805 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf1486_1805
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF1486_1805
  read_length: 150
  coverage: 16549.1
  platform: illumina

fragment:
  model: normal
  mean: 153.3
  sd: 48.9

quality:
  mean_quality: 39
  tail_decay: 0.0041

tumour:
  purity: 0.297171
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 6.85
  family_size_sd: 1.73

chromosomes:
  - chr1

seed: 422473
