# varforge config: INVDEL_ML3_TRAIN_VAF0181_1759 — VAF 1.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0181_1759
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0181_1759
  read_length: 150
  coverage: 1101.0
  platform: illumina

fragment:
  model: normal
  mean: 173.5
  sd: 48.5

quality:
  mean_quality: 36
  tail_decay: 0.0041

tumour:
  purity: 0.036153
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 4.18
  family_size_sd: 1.00

chromosomes:
  - chr1

seed: 472311
