# varforge config: INVDEL_ML3_TRAIN_VAF0003_0334 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0003_0334
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0003_0334
  read_length: 150
  coverage: 1937.9
  platform: illumina

fragment:
  model: normal
  mean: 224.1
  sd: 49.7

quality:
  mean_quality: 31
  tail_decay: 0.0034

tumour:
  purity: 0.000664
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 1.71
  family_size_sd: 0.81

chromosomes:
  - chr1

seed: 487175
