# varforge config: INVDEL_ML3_TRAIN_VAF0045_1846 — VAF 0.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0045_1846
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0045_1846
  read_length: 150
  coverage: 1395.0
  platform: illumina

fragment:
  model: normal
  mean: 180.1
  sd: 23.6

quality:
  mean_quality: 31
  tail_decay: 0.0013

tumour:
  purity: 0.009067
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0050_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.57
  family_size_sd: 0.57

chromosomes:
  - chr1

seed: 482271
