# varforge config: INVDEL_ML3_TRAIN_VAF0004_1606 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0004_1606
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0004_1606
  read_length: 150
  coverage: 849.4
  platform: illumina

fragment:
  model: normal
  mean: 237.9
  sd: 26.3

quality:
  mean_quality: 33
  tail_decay: 0.0035

tumour:
  purity: 0.000799
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 4.38
  family_size_sd: 1.15

chromosomes:
  - chr1

seed: 450724
