# varforge config: INVDEL_ML3_TRAIN_VAF0026_1350 — VAF 0.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0026_1350
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0026_1350
  read_length: 150
  coverage: 6834.7
  platform: illumina

fragment:
  model: normal
  mean: 233.5
  sd: 50.0

quality:
  mean_quality: 35
  tail_decay: 0.0039

tumour:
  purity: 0.005184
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0025_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 3.15
  family_size_sd: 1.63

chromosomes:
  - chr1

seed: 425564
