# varforge config: INVDEL_ML3_TRAIN_VAF0042_0988 — VAF 0.4000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0042_0988
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0042_0988
  read_length: 150
  coverage: 3316.6
  platform: illumina

fragment:
  model: normal
  mean: 179.3
  sd: 33.3

quality:
  mean_quality: 38
  tail_decay: 0.0038

tumour:
  purity: 0.008327
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0040_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 5.27
  family_size_sd: 2.67

chromosomes:
  - chr1

seed: 431419
