# varforge config: INVDEL_ML3_TRAIN_VAF0004_1129 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0004_1129
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0004_1129
  read_length: 150
  coverage: 548.7
  platform: illumina

fragment:
  model: normal
  mean: 135.0
  sd: 30.0

quality:
  mean_quality: 31
  tail_decay: 0.0025

tumour:
  purity: 0.000702
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 5.73
  family_size_sd: 2.24

chromosomes:
  - chr1

seed: 470667
