# varforge config: INVDEL_ML3_TRAIN_VAF0039_0683 — VAF 0.4000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0039_0683
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0039_0683
  read_length: 150
  coverage: 7203.4
  platform: illumina

fragment:
  model: normal
  mean: 249.7
  sd: 34.5

quality:
  mean_quality: 34
  tail_decay: 0.0037

tumour:
  purity: 0.007802
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0040_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 7.13
  family_size_sd: 3.16

chromosomes:
  - chr1

seed: 449928
