# varforge config: INVDEL_ML3_TRAIN_VAF0246_1666 — VAF 2.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0246_1666
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0246_1666
  read_length: 150
  coverage: 5376.3
  platform: illumina

fragment:
  model: normal
  mean: 247.3
  sd: 23.1

quality:
  mean_quality: 38
  tail_decay: 0.0027

tumour:
  purity: 0.049212
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0250_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 1.66
  family_size_sd: 0.75

chromosomes:
  - chr1

seed: 482943
