# varforge config: INVDEL_ML3_TRAIN_VAF0004_0070 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_invdel_ml3_train_vaf0004_0070
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: INVDEL_ML3_TRAIN_VAF0004_0070
  read_length: 150
  coverage: 982.2
  platform: illumina

fragment:
  model: normal
  mean: 179.7
  sd: 42.0

quality:
  mean_quality: 36
  tail_decay: 0.0036

tumour:
  purity: 0.000857
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_invdel_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 8.64
  family_size_sd: 2.21

chromosomes:
  - chr1

seed: 410164
