# varforge config: SNV_ML3_TRAIN_VAF0647_0711 — VAF 6.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0647_0711
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0647_0711
  read_length: 150
  coverage: 7268.7
  platform: illumina

fragment:
  model: normal
  mean: 243.7
  sd: 42.2

quality:
  mean_quality: 31
  tail_decay: 0.0030

tumour:
  purity: 0.129301
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0600_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 8.10
  family_size_sd: 3.46

chromosomes:
  - chr1

seed: 480015
