# varforge config: SNV_ML3_TRAIN_VAF0656_1029 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0656_1029
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0656_1029
  read_length: 150
  coverage: 765.3
  platform: illumina

fragment:
  model: normal
  mean: 189.2
  sd: 31.9

quality:
  mean_quality: 34
  tail_decay: 0.0016

tumour:
  purity: 0.131210
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 1.81
  family_size_sd: 0.71

chromosomes:
  - chr1

seed: 418842
