# varforge config: SNV_ML3_TRAIN_VAF0050_1509 — VAF 0.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0050_1509
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0050_1509
  read_length: 150
  coverage: 602.4
  platform: illumina

fragment:
  model: normal
  mean: 189.3
  sd: 27.0

quality:
  mean_quality: 39
  tail_decay: 0.0034

tumour:
  purity: 0.010038
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0050_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 8.39
  family_size_sd: 4.83

chromosomes:
  - chr1

seed: 476735
