# varforge config: SNV_ML3_TRAIN_VAF0743_1329 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0743_1329
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0743_1329
  read_length: 150
  coverage: 7083.8
  platform: illumina

fragment:
  model: normal
  mean: 251.3
  sd: 35.6

quality:
  mean_quality: 40
  tail_decay: 0.0023

tumour:
  purity: 0.148524
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.50
  family_size_sd: 0.97

chromosomes:
  - chr1

seed: 420582
