# varforge config: SNV_ML3_TRAIN_VAF1331_0411 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf1331_0411
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF1331_0411
  read_length: 150
  coverage: 15718.7
  platform: illumina

fragment:
  model: normal
  mean: 164.5
  sd: 37.9

quality:
  mean_quality: 32
  tail_decay: 0.0033

tumour:
  purity: 0.266291
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 1.54
  family_size_sd: 0.81

chromosomes:
  - chr1

seed: 407216
