# varforge config: SNV_ML3_TRAIN_VAF0605_1149 — VAF 6.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0605_1149
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0605_1149
  read_length: 150
  coverage: 15934.1
  platform: illumina

fragment:
  model: normal
  mean: 252.6
  sd: 16.8

quality:
  mean_quality: 32
  tail_decay: 0.0015

tumour:
  purity: 0.121041
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0600_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 4.20
  family_size_sd: 1.83

chromosomes:
  - chr1

seed: 473664
