# varforge config: SNV_ML3_TRAIN_VAF0061_0196 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0061_0196
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0061_0196
  read_length: 150
  coverage: 6297.2
  platform: illumina

fragment:
  model: normal
  mean: 202.1
  sd: 30.6

quality:
  mean_quality: 38
  tail_decay: 0.0022

tumour:
  purity: 0.012138
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0060_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 2.31
  family_size_sd: 0.64

chromosomes:
  - chr1

seed: 487052
