# varforge config: SNV_ML3_TRAIN_VAF0365_1789 — VAF 3.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0365_1789
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0365_1789
  read_length: 150
  coverage: 15360.7
  platform: illumina

fragment:
  model: normal
  mean: 206.7
  sd: 48.1

quality:
  mean_quality: 32
  tail_decay: 0.0023

tumour:
  purity: 0.072900
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0350_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 5.32
  family_size_sd: 1.46

chromosomes:
  - chr1

seed: 480857
