# varforge config: SNV_ML3_TRAIN_VAF0023_1809 — VAF 0.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0023_1809
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0023_1809
  read_length: 150
  coverage: 953.5
  platform: illumina

fragment:
  model: normal
  mean: 204.2
  sd: 33.2

quality:
  mean_quality: 34
  tail_decay: 0.0040

tumour:
  purity: 0.004615
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0025_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 8.88
  family_size_sd: 5.20

chromosomes:
  - chr1

seed: 470045
