# varforge config: SNV_ML3_TRAIN_VAF0026_0893 — VAF 0.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0026_0893
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0026_0893
  read_length: 150
  coverage: 1705.1
  platform: illumina

fragment:
  model: normal
  mean: 153.3
  sd: 30.9

quality:
  mean_quality: 40
  tail_decay: 0.0038

tumour:
  purity: 0.005169
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0025_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 3.50
  family_size_sd: 0.86

chromosomes:
  - chr1

seed: 447429
