# varforge config: SNV_ML3_TRAIN_VAF0083_1166 — VAF 0.7500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0083_1166
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0083_1166
  read_length: 150
  coverage: 716.4
  platform: illumina

fragment:
  model: normal
  mean: 181.7
  sd: 39.4

quality:
  mean_quality: 37
  tail_decay: 0.0026

tumour:
  purity: 0.016662
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0075_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 3.93
  family_size_sd: 2.16

chromosomes:
  - chr1

seed: 480719
