# varforge config: SNV_ML3_TRAIN_VAF0493_0673 — VAF 5.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0493_0673
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0493_0673
  read_length: 150
  coverage: 4891.6
  platform: illumina

fragment:
  model: normal
  mean: 140.6
  sd: 23.4

quality:
  mean_quality: 40
  tail_decay: 0.0037

tumour:
  purity: 0.098635
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0500_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 1.56
  family_size_sd: 0.87

chromosomes:
  - chr1

seed: 456198
