# varforge config: SNV_ML3_TRAIN_VAF1402_0726 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf1402_0726
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF1402_0726
  read_length: 150
  coverage: 6315.6
  platform: illumina

fragment:
  model: normal
  mean: 225.2
  sd: 37.7

quality:
  mean_quality: 34
  tail_decay: 0.0046

tumour:
  purity: 0.280432
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 3.37
  family_size_sd: 1.89

chromosomes:
  - chr1

seed: 485338
