# varforge config: SNV_ML3_TRAIN_VAF0142_1897 — VAF 1.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0142_1897
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0142_1897
  read_length: 150
  coverage: 557.7
  platform: illumina

fragment:
  model: normal
  mean: 232.4
  sd: 34.2

quality:
  mean_quality: 32
  tail_decay: 0.0047

tumour:
  purity: 0.028400
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0150_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 2.64
  family_size_sd: 1.02

chromosomes:
  - chr1

seed: 437242
