# varforge config: SNV_ML3_TRAIN_VAF0041_0050 — VAF 0.4000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0041_0050
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0041_0050
  read_length: 150
  coverage: 10764.7
  platform: illumina

fragment:
  model: normal
  mean: 195.0
  sd: 43.6

quality:
  mean_quality: 30
  tail_decay: 0.0050

tumour:
  purity: 0.008118
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0040_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 6.03
  family_size_sd: 2.99

chromosomes:
  - chr1

seed: 458507
