# varforge config: SNV_ML3_TRAIN_VAF0003_0042 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0003_0042
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0003_0042
  read_length: 150
  coverage: 6502.1
  platform: illumina

fragment:
  model: normal
  mean: 175.3
  sd: 22.5

quality:
  mean_quality: 30
  tail_decay: 0.0044

tumour:
  purity: 0.000671
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.00
  family_size_sd: 1.11

chromosomes:
  - chr1

seed: 443965
