# varforge config: SNV_ML3_TRAIN_VAF0723_1830 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0723_1830
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0723_1830
  read_length: 150
  coverage: 10241.0
  platform: illumina

fragment:
  model: normal
  mean: 203.4
  sd: 15.2

quality:
  mean_quality: 37
  tail_decay: 0.0013

tumour:
  purity: 0.144676
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 9.17
  family_size_sd: 4.70

chromosomes:
  - chr1

seed: 439379
