# varforge config: SNV_ML3_TRAIN_VAF0092_0690 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0092_0690
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0092_0690
  read_length: 150
  coverage: 724.4
  platform: illumina

fragment:
  model: normal
  mean: 219.4
  sd: 37.9

quality:
  mean_quality: 39
  tail_decay: 0.0038

tumour:
  purity: 0.018378
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0100_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 2.49
  family_size_sd: 0.59

chromosomes:
  - chr1

seed: 460937
