# varforge config: SNV_ML3_TRAIN_VAF0785_0834 — VAF 8.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0785_0834
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0785_0834
  read_length: 150
  coverage: 6941.1
  platform: illumina

fragment:
  model: normal
  mean: 224.3
  sd: 32.1

quality:
  mean_quality: 31
  tail_decay: 0.0040

tumour:
  purity: 0.156991
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0800_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 9.58
  family_size_sd: 5.73

chromosomes:
  - chr1

seed: 418972
