# varforge config: SNV_ML3_TRAIN_VAF0275_0203 — VAF 3.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0275_0203
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0275_0203
  read_length: 150
  coverage: 2821.2
  platform: illumina

fragment:
  model: normal
  mean: 213.9
  sd: 33.3

quality:
  mean_quality: 32
  tail_decay: 0.0039

tumour:
  purity: 0.055090
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0300_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 6.35
  family_size_sd: 3.45

chromosomes:
  - chr1

seed: 406197
