# varforge config: SNV_ML3_TRAIN_VAF0007_0811 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0007_0811
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0007_0811
  read_length: 150
  coverage: 3071.2
  platform: illumina

fragment:
  model: normal
  mean: 202.4
  sd: 34.6

quality:
  mean_quality: 34
  tail_decay: 0.0011

tumour:
  purity: 0.001365
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 2.35
  family_size_sd: 0.71

chromosomes:
  - chr1

seed: 407461
