# varforge config: SNV_ML3_TRAIN_VAF0739_1541 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0739_1541
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0739_1541
  read_length: 150
  coverage: 943.7
  platform: illumina

fragment:
  model: normal
  mean: 268.5
  sd: 32.6

quality:
  mean_quality: 33
  tail_decay: 0.0018

tumour:
  purity: 0.147708
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 3.14
  family_size_sd: 1.62

chromosomes:
  - chr1

seed: 441329
