# varforge config: SNV_ML3_TRAIN_VAF0352_0579 — VAF 3.5000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0352_0579
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0352_0579
  read_length: 150
  coverage: 2218.3
  platform: illumina

fragment:
  model: normal
  mean: 270.8
  sd: 42.5

quality:
  mean_quality: 33
  tail_decay: 0.0018

tumour:
  purity: 0.070342
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0350_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 5.38
  family_size_sd: 1.58

chromosomes:
  - chr1

seed: 474141
