# varforge config: SNV_ML3_TRAIN_VAF0733_1296 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0733_1296
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0733_1296
  read_length: 150
  coverage: 537.8
  platform: illumina

fragment:
  model: normal
  mean: 167.1
  sd: 42.7

quality:
  mean_quality: 31
  tail_decay: 0.0041

tumour:
  purity: 0.146640
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 4.25
  family_size_sd: 2.09

chromosomes:
  - chr1

seed: 471346
