# varforge config: SNV_ML3_TRAIN_VAF0004_0560 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0004_0560
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0004_0560
  read_length: 150
  coverage: 5901.2
  platform: illumina

fragment:
  model: normal
  mean: 135.0
  sd: 18.8

quality:
  mean_quality: 36
  tail_decay: 0.0037

tumour:
  purity: 0.000763
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 1.54
  family_size_sd: 0.42

chromosomes:
  - chr1

seed: 486992
