# varforge config: SNV_ML3_TRAIN_VAF1276_0167 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf1276_0167
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF1276_0167
  read_length: 150
  coverage: 736.0
  platform: illumina

fragment:
  model: normal
  mean: 242.8
  sd: 45.3

quality:
  mean_quality: 35
  tail_decay: 0.0030

tumour:
  purity: 0.255182
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 4.95
  family_size_sd: 1.30

chromosomes:
  - chr1

seed: 471140
