# varforge config: SNV_ML3_TRAIN_VAF0745_1916 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0745_1916
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0745_1916
  read_length: 150
  coverage: 551.3
  platform: illumina

fragment:
  model: normal
  mean: 158.9
  sd: 34.5

quality:
  mean_quality: 37
  tail_decay: 0.0025

tumour:
  purity: 0.148970
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 5.90
  family_size_sd: 1.38

chromosomes:
  - chr1

seed: 481763
