# varforge config: SNV_ML3_TRAIN_VAF0697_0490 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0697_0490
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0697_0490
  read_length: 150
  coverage: 3638.6
  platform: illumina

fragment:
  model: normal
  mean: 143.3
  sd: 17.2

quality:
  mean_quality: 36
  tail_decay: 0.0043

tumour:
  purity: 0.139495
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 2.60
  family_size_sd: 1.13

chromosomes:
  - chr1

seed: 472788
