# varforge config: SNV_ML3_TRAIN_VAF0433_1856 — VAF 4.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0433_1856
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0433_1856
  read_length: 150
  coverage: 14206.2
  platform: illumina

fragment:
  model: normal
  mean: 254.9
  sd: 47.4

quality:
  mean_quality: 33
  tail_decay: 0.0042

tumour:
  purity: 0.086580
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0400_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 2.90
  family_size_sd: 1.69

chromosomes:
  - chr1

seed: 488368
