# varforge config: SNV_ML3_TRAIN_VAF0018_0207 — VAF 0.2000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0018_0207
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0018_0207
  read_length: 150
  coverage: 700.3
  platform: illumina

fragment:
  model: normal
  mean: 187.6
  sd: 28.6

quality:
  mean_quality: 32
  tail_decay: 0.0047

tumour:
  purity: 0.003608
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0020_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 7.68
  family_size_sd: 3.32

chromosomes:
  - chr1

seed: 485820
