# varforge config: SNV_ML3_TRAIN_VAF0110_1346 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0110_1346
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0110_1346
  read_length: 150
  coverage: 1538.6
  platform: illumina

fragment:
  model: normal
  mean: 133.4
  sd: 19.4

quality:
  mean_quality: 35
  tail_decay: 0.0045

tumour:
  purity: 0.021906
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0100_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 3.52
  family_size_sd: 1.69

chromosomes:
  - chr1

seed: 424555
