# varforge config: SNV_ML3_TRAIN_VAF0666_1420 — VAF 7.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0666_1420
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0666_1420
  read_length: 150
  coverage: 1047.4
  platform: illumina

fragment:
  model: normal
  mean: 181.1
  sd: 29.0

quality:
  mean_quality: 36
  tail_decay: 0.0011

tumour:
  purity: 0.133150
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 4.05
  family_size_sd: 2.38

chromosomes:
  - chr1

seed: 443250
