# varforge config: SNV_ML3_TRAIN_VAF0059_1828 — VAF 0.6000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0059_1828
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0059_1828
  read_length: 150
  coverage: 6112.2
  platform: illumina

fragment:
  model: normal
  mean: 266.8
  sd: 17.1

quality:
  mean_quality: 36
  tail_decay: 0.0013

tumour:
  purity: 0.011746
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0060_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 5.07
  family_size_sd: 1.59

chromosomes:
  - chr1

seed: 462844
