# varforge config: SNV_ML3_TRAIN_VAF1099_0833 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf1099_0833
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF1099_0833
  read_length: 150
  coverage: 743.4
  platform: illumina

fragment:
  model: normal
  mean: 242.8
  sd: 46.0

quality:
  mean_quality: 33
  tail_decay: 0.0023

tumour:
  purity: 0.219816
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 7.51
  family_size_sd: 3.45

chromosomes:
  - chr1

seed: 417188
