# varforge config: SNV_ML3_TRAIN_VAF0007_1995 — VAF 0.0500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0007_1995
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0007_1995
  read_length: 150
  coverage: 1500.0
  platform: illumina

fragment:
  model: normal
  mean: 196.3
  sd: 48.4

quality:
  mean_quality: 31
  tail_decay: 0.0024

tumour:
  purity: 0.001344
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 9.72
  family_size_sd: 3.07

chromosomes:
  - chr1

seed: 406239
