# varforge config: SNV_ML3_TRAIN_VAF0137_0515 — VAF 1.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0137_0515
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0137_0515
  read_length: 150
  coverage: 632.3
  platform: illumina

fragment:
  model: normal
  mean: 186.6
  sd: 17.7

quality:
  mean_quality: 35
  tail_decay: 0.0026

tumour:
  purity: 0.027309
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 5.36
  family_size_sd: 2.10

chromosomes:
  - chr1

seed: 463173
