# varforge config: SNV_ML3_TRAIN_VAF0034_0355 — VAF 0.3500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0034_0355
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0034_0355
  read_length: 150
  coverage: 1239.6
  platform: illumina

fragment:
  model: normal
  mean: 152.4
  sd: 34.3

quality:
  mean_quality: 30
  tail_decay: 0.0028

tumour:
  purity: 0.006754
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 5.55
  family_size_sd: 2.89

chromosomes:
  - chr1

seed: 418431
