# varforge config: SNV_ML3_TRAIN_VAF1076_1832 — VAF 10.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf1076_1832
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF1076_1832
  read_length: 150
  coverage: 11013.1
  platform: illumina

fragment:
  model: normal
  mean: 175.4
  sd: 45.5

quality:
  mean_quality: 38
  tail_decay: 0.0026

tumour:
  purity: 0.215176
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 2.10
  family_size_sd: 1.18

chromosomes:
  - chr1

seed: 440831
