# varforge config: SNV_ML3_TRAIN_VAF0019_0882 — VAF 0.2000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0019_0882
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0019_0882
  read_length: 150
  coverage: 2142.1
  platform: illumina

fragment:
  model: normal
  mean: 178.6
  sd: 34.4

quality:
  mean_quality: 30
  tail_decay: 0.0029

tumour:
  purity: 0.003733
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0020_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.30
  family_size_sd: 1.65

chromosomes:
  - chr1

seed: 441947
