# varforge config: SNV_ML3_TRAIN_VAF0122_0197 — VAF 1.2500%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0122_0197
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0122_0197
  read_length: 150
  coverage: 797.7
  platform: illumina

fragment:
  model: normal
  mean: 273.9
  sd: 18.3

quality:
  mean_quality: 31
  tail_decay: 0.0014

tumour:
  purity: 0.024420
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 6.13
  family_size_sd: 2.61

chromosomes:
  - chr1

seed: 499326
