# varforge config: SNV_ML3_TRAIN_VAF0108_1508 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0108_1508
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0108_1508
  read_length: 150
  coverage: 1978.2
  platform: illumina

fragment:
  model: normal
  mean: 248.6
  sd: 39.8

quality:
  mean_quality: 34
  tail_decay: 0.0024

tumour:
  purity: 0.021689
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 8.45
  family_size_sd: 4.43

chromosomes:
  - chr1

seed: 471912
