# varforge config: SNV_ML3_TRAIN_VAF0111_1368 — VAF 1.0000%
reference: docs/benchmarking/snvindel/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_snv_ml3_train_vaf0111_1368
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SNV_ML3_TRAIN_VAF0111_1368
  read_length: 150
  coverage: 6623.3
  platform: illumina

fragment:
  model: normal
  mean: 253.9
  sd: 19.3

quality:
  mean_quality: 30
  tail_decay: 0.0020

tumour:
  purity: 0.022130
  ploidy: 2

mutations:
  vcf: docs/benchmarking/snvindel/data/truth_snvs_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 1.55
  family_size_sd: 0.57

chromosomes:
  - chr1

seed: 414380
