# varforge config: SV_ML3_TRAIN_VAF0155_1518 — VAF 1.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0155_1518
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0155_1518
  read_length: 150
  coverage: 2321.7
  platform: illumina

fragment:
  model: normal
  mean: 187.6
  sd: 46.6

quality:
  mean_quality: 39
  tail_decay: 0.0036

tumour:
  purity: 0.030963
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0150_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 4.52
  family_size_sd: 1.30

chromosomes:
  - chr1

seed: 431416
