# varforge config: SV_ML3_TRAIN_VAF0524_0863 — VAF 5.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0524_0863
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0524_0863
  read_length: 150
  coverage: 717.3
  platform: illumina

fragment:
  model: normal
  mean: 197.7
  sd: 31.1

quality:
  mean_quality: 39
  tail_decay: 0.0018

tumour:
  purity: 0.104888
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0500_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 5.52
  family_size_sd: 1.37

chromosomes:
  - chr1

seed: 486378
