# varforge config: SV_ML3_TRAIN_VAF0186_0312 — VAF 1.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0186_0312
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0186_0312
  read_length: 150
  coverage: 12805.7
  platform: illumina

fragment:
  model: normal
  mean: 268.5
  sd: 31.2

quality:
  mean_quality: 33
  tail_decay: 0.0029

tumour:
  purity: 0.037240
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 2.49
  family_size_sd: 0.79

chromosomes:
  - chr1

seed: 474658
