# varforge config: SV_ML3_TRAIN_VAF0328_1352 — VAF 3.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0328_1352
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0328_1352
  read_length: 150
  coverage: 2712.2
  platform: illumina

fragment:
  model: normal
  mean: 229.7
  sd: 26.3

quality:
  mean_quality: 30
  tail_decay: 0.0039

tumour:
  purity: 0.065552
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0350_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 1.92
  family_size_sd: 0.71

chromosomes:
  - chr1

seed: 499344
