# varforge config: SV_ML3_TRAIN_VAF0013_0034 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0013_0034
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0013_0034
  read_length: 150
  coverage: 616.6
  platform: illumina

fragment:
  model: normal
  mean: 243.5
  sd: 33.9

quality:
  mean_quality: 38
  tail_decay: 0.0039

tumour:
  purity: 0.002595
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 5.63
  family_size_sd: 2.54

chromosomes:
  - chr1

seed: 481797
