# varforge config: SV_ML3_TRAIN_VAF0017_0012 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0017_0012
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0017_0012
  read_length: 150
  coverage: 648.2
  platform: illumina

fragment:
  model: normal
  mean: 192.9
  sd: 43.1

quality:
  mean_quality: 31
  tail_decay: 0.0034

tumour:
  purity: 0.003398
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 2.61
  family_size_sd: 1.19

chromosomes:
  - chr1

seed: 477482
