# varforge config: SV_ML3_TRAIN_VAF0748_1564 — VAF 7.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0748_1564
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0748_1564
  read_length: 150
  coverage: 2478.2
  platform: illumina

fragment:
  model: normal
  mean: 134.6
  sd: 36.0

quality:
  mean_quality: 40
  tail_decay: 0.0044

tumour:
  purity: 0.149687
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 5.81
  family_size_sd: 2.00

chromosomes:
  - chr1

seed: 448761
