# varforge config: SV_ML3_TRAIN_VAF0016_1034 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0016_1034
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0016_1034
  read_length: 150
  coverage: 5852.7
  platform: illumina

fragment:
  model: normal
  mean: 144.7
  sd: 38.6

quality:
  mean_quality: 33
  tail_decay: 0.0028

tumour:
  purity: 0.003190
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 4.88
  family_size_sd: 1.95

chromosomes:
  - chr1

seed: 411017
