# varforge config: SV_ML3_TRAIN_VAF0371_1317 — VAF 3.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0371_1317
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0371_1317
  read_length: 150
  coverage: 2523.8
  platform: illumina

fragment:
  model: normal
  mean: 145.9
  sd: 15.4

quality:
  mean_quality: 34
  tail_decay: 0.0044

tumour:
  purity: 0.074147
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0350_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 3.02
  family_size_sd: 1.56

chromosomes:
  - chr1

seed: 400885
