# varforge config: SV_ML3_TRAIN_VAF0415_1938 — VAF 4.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0415_1938
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0415_1938
  read_length: 150
  coverage: 881.1
  platform: illumina

fragment:
  model: normal
  mean: 217.2
  sd: 45.9

quality:
  mean_quality: 39
  tail_decay: 0.0036

tumour:
  purity: 0.083058
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0400_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.35
  family_size_sd: 1.32

chromosomes:
  - chr1

seed: 490281
