# varforge config: SV_ML3_TRAIN_VAF1102_0015 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf1102_0015
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF1102_0015
  read_length: 150
  coverage: 10027.5
  platform: illumina

fragment:
  model: normal
  mean: 262.2
  sd: 22.6

quality:
  mean_quality: 39
  tail_decay: 0.0049

tumour:
  purity: 0.220459
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 1.87
  family_size_sd: 0.56

chromosomes:
  - chr1

seed: 405455
