# varforge config: SV_ML3_TRAIN_VAF0015_1530 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0015_1530
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0015_1530
  read_length: 150
  coverage: 1911.6
  platform: illumina

fragment:
  model: normal
  mean: 180.0
  sd: 42.1

quality:
  mean_quality: 33
  tail_decay: 0.0041

tumour:
  purity: 0.002958
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0015_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 6.40
  family_size_sd: 2.16

chromosomes:
  - chr1

seed: 477030
