# varforge config: SV_ML3_TRAIN_VAF0597_0291 — VAF 6.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0597_0291
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0597_0291
  read_length: 150
  coverage: 2567.7
  platform: illumina

fragment:
  model: normal
  mean: 252.6
  sd: 24.8

quality:
  mean_quality: 33
  tail_decay: 0.0033

tumour:
  purity: 0.119370
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0600_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 5.98
  family_size_sd: 2.55

chromosomes:
  - chr1

seed: 402759
