# varforge config: SV_ML3_TRAIN_VAF0925_0164 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0925_0164
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0925_0164
  read_length: 150
  coverage: 7204.6
  platform: illumina

fragment:
  model: normal
  mean: 271.3
  sd: 47.9

quality:
  mean_quality: 39
  tail_decay: 0.0044

tumour:
  purity: 0.185095
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 2.45
  family_size_sd: 0.59

chromosomes:
  - chr1

seed: 467154
