# varforge config: SV_ML3_TRAIN_VAF0141_1664 — VAF 1.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0141_1664
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0141_1664
  read_length: 150
  coverage: 607.0
  platform: illumina

fragment:
  model: normal
  mean: 151.1
  sd: 43.2

quality:
  mean_quality: 32
  tail_decay: 0.0012

tumour:
  purity: 0.028241
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0150_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 5.24
  family_size_sd: 1.43

chromosomes:
  - chr1

seed: 494396
