# varforge config: SV_ML3_TRAIN_VAF0013_0998 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0013_0998
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0013_0998
  read_length: 150
  coverage: 1916.6
  platform: illumina

fragment:
  model: normal
  mean: 248.6
  sd: 18.3

quality:
  mean_quality: 31
  tail_decay: 0.0027

tumour:
  purity: 0.002599
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 3.53
  family_size_sd: 0.88

chromosomes:
  - chr1

seed: 420398
