# varforge config: SV_ML3_TRAIN_VAF0007_0729 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0007_0729
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0007_0729
  read_length: 150
  coverage: 3515.5
  platform: illumina

fragment:
  model: normal
  mean: 155.8
  sd: 49.4

quality:
  mean_quality: 35
  tail_decay: 0.0040

tumour:
  purity: 0.001423
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 4.50
  family_size_sd: 2.50

chromosomes:
  - chr1

seed: 455424
