# varforge config: SV_ML3_TRAIN_VAF0022_1463 — VAF 0.2000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0022_1463
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0022_1463
  read_length: 150
  coverage: 13053.4
  platform: illumina

fragment:
  model: normal
  mean: 238.0
  sd: 20.5

quality:
  mean_quality: 31
  tail_decay: 0.0016

tumour:
  purity: 0.004393
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0020_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 7.49
  family_size_sd: 2.71

chromosomes:
  - chr1

seed: 419994
