# varforge config: SV_ML3_TRAIN_VAF0016_0428 — VAF 0.1500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0016_0428
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0016_0428
  read_length: 150
  coverage: 825.9
  platform: illumina

fragment:
  model: normal
  mean: 273.0
  sd: 38.9

quality:
  mean_quality: 36
  tail_decay: 0.0039

tumour:
  purity: 0.003232
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0015_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 8.13
  family_size_sd: 4.24

chromosomes:
  - chr1

seed: 428133
