# varforge config: SV_ML3_TRAIN_VAF0047_1993 — VAF 0.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0047_1993
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0047_1993
  read_length: 150
  coverage: 3303.8
  platform: illumina

fragment:
  model: normal
  mean: 230.1
  sd: 42.8

quality:
  mean_quality: 30
  tail_decay: 0.0036

tumour:
  purity: 0.009484
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0050_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 1.75
  family_size_sd: 0.63

chromosomes:
  - chr1

seed: 467441
