# varforge config: SV_ML3_TRAIN_VAF0719_0858 — VAF 7.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0719_0858
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0719_0858
  read_length: 150
  coverage: 5162.4
  platform: illumina

fragment:
  model: normal
  mean: 225.5
  sd: 15.5

quality:
  mean_quality: 40
  tail_decay: 0.0037

tumour:
  purity: 0.143705
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0700_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 7.24
  family_size_sd: 3.63

chromosomes:
  - chr1

seed: 490829
