# varforge config: SV_ML3_TRAIN_VAF1309_1531 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf1309_1531
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF1309_1531
  read_length: 150
  coverage: 4655.9
  platform: illumina

fragment:
  model: normal
  mean: 171.6
  sd: 18.4

quality:
  mean_quality: 31
  tail_decay: 0.0042

tumour:
  purity: 0.261829
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 4.46
  family_size_sd: 2.29

chromosomes:
  - chr1

seed: 436928
