# varforge config: SV_ML3_TRAIN_VAF0093_0031 — VAF 1.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0093_0031
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0093_0031
  read_length: 150
  coverage: 2436.5
  platform: illumina

fragment:
  model: normal
  mean: 155.8
  sd: 31.5

quality:
  mean_quality: 39
  tail_decay: 0.0023

tumour:
  purity: 0.018607
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0100_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 11
  family_size_mean: 7.44
  family_size_sd: 3.39

chromosomes:
  - chr1

seed: 412033
