# varforge config: SV_ML3_TRAIN_VAF0067_0958 — VAF 0.6000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0067_0958
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0067_0958
  read_length: 150
  coverage: 1477.7
  platform: illumina

fragment:
  model: normal
  mean: 170.6
  sd: 16.1

quality:
  mean_quality: 31
  tail_decay: 0.0014

tumour:
  purity: 0.013392
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0060_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 1.80
  family_size_sd: 0.38

chromosomes:
  - chr1

seed: 431073
