# varforge config: SV_ML3_TRAIN_VAF0061_1873 — VAF 0.6000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0061_1873
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0061_1873
  read_length: 150
  coverage: 19782.3
  platform: illumina

fragment:
  model: normal
  mean: 203.4
  sd: 38.0

quality:
  mean_quality: 38
  tail_decay: 0.0045

tumour:
  purity: 0.012149
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0060_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 9.64
  family_size_sd: 5.09

chromosomes:
  - chr1

seed: 404774
