# varforge config: SV_ML3_TRAIN_VAF0134_0319 — VAF 1.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0134_0319
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0134_0319
  read_length: 150
  coverage: 884.0
  platform: illumina

fragment:
  model: normal
  mean: 203.4
  sd: 18.1

quality:
  mean_quality: 34
  tail_decay: 0.0016

tumour:
  purity: 0.026865
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0125_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 2.20
  family_size_sd: 0.82

chromosomes:
  - chr1

seed: 456120
