# varforge config: SV_ML3_TRAIN_VAF0359_0332 — VAF 3.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0359_0332
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0359_0332
  read_length: 150
  coverage: 8234.3
  platform: illumina

fragment:
  model: normal
  mean: 264.8
  sd: 42.4

quality:
  mean_quality: 38
  tail_decay: 0.0041

tumour:
  purity: 0.071897
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0350_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 7.17
  family_size_sd: 3.73

chromosomes:
  - chr1

seed: 451470
