# varforge config: SV_ML3_TRAIN_VAF0116_1985 — VAF 1.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0116_1985
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0116_1985
  read_length: 150
  coverage: 611.2
  platform: illumina

fragment:
  model: normal
  mean: 185.2
  sd: 21.6

quality:
  mean_quality: 38
  tail_decay: 0.0022

tumour:
  purity: 0.023187
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 14
  family_size_mean: 7.13
  family_size_sd: 1.65

chromosomes:
  - chr1

seed: 419011
