# varforge config: SV_ML3_TRAIN_VAF0034_1025 — VAF 0.3500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0034_1025
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0034_1025
  read_length: 150
  coverage: 16175.8
  platform: illumina

fragment:
  model: normal
  mean: 223.5
  sd: 41.0

quality:
  mean_quality: 37
  tail_decay: 0.0044

tumour:
  purity: 0.006702
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0035_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 3.23
  family_size_sd: 1.49

chromosomes:
  - chr1

seed: 431859
