# varforge config: SV_ML3_TRAIN_VAF0011_0973 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0011_0973
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0011_0973
  read_length: 150
  coverage: 764.0
  platform: illumina

fragment:
  model: normal
  mean: 213.3
  sd: 39.4

quality:
  mean_quality: 32
  tail_decay: 0.0022

tumour:
  purity: 0.002191
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0010_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.66
  family_size_sd: 1.44

chromosomes:
  - chr1

seed: 481993
