# varforge config: SV_ML3_TRAIN_VAF0048_0794 — VAF 0.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0048_0794
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0048_0794
  read_length: 150
  coverage: 6061.9
  platform: illumina

fragment:
  model: normal
  mean: 243.5
  sd: 33.6

quality:
  mean_quality: 33
  tail_decay: 0.0012

tumour:
  purity: 0.009696
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0050_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 5
  family_size_mean: 2.28
  family_size_sd: 0.83

chromosomes:
  - chr1

seed: 465441
