# varforge config: SV_ML3_TRAIN_VAF0005_1595 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0005_1595
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0005_1595
  read_length: 150
  coverage: 12645.9
  platform: illumina

fragment:
  model: normal
  mean: 249.6
  sd: 21.4

quality:
  mean_quality: 31
  tail_decay: 0.0036

tumour:
  purity: 0.000944
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 2.52
  family_size_sd: 1.48

chromosomes:
  - chr1

seed: 462962
