# varforge config: SV_ML3_TRAIN_VAF0049_1132 — VAF 0.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0049_1132
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0049_1132
  read_length: 150
  coverage: 12618.5
  platform: illumina

fragment:
  model: normal
  mean: 212.9
  sd: 20.3

quality:
  mean_quality: 38
  tail_decay: 0.0016

tumour:
  purity: 0.009773
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0050_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 2.57
  family_size_sd: 0.68

chromosomes:
  - chr1

seed: 488482
