# varforge config: SV_ML3_TRAIN_VAF0113_0641 — VAF 1.2500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0113_0641
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0113_0641
  read_length: 150
  coverage: 1289.4
  platform: illumina

fragment:
  model: normal
  mean: 244.6
  sd: 15.9

quality:
  mean_quality: 36
  tail_decay: 0.0032

tumour:
  purity: 0.022597
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0125_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 7
  family_size_mean: 4.58
  family_size_sd: 1.18

chromosomes:
  - chr1

seed: 463201
