# varforge config: SV_ML3_TRAIN_VAF0019_1223 — VAF 0.2000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0019_1223
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0019_1223
  read_length: 150
  coverage: 511.0
  platform: illumina

fragment:
  model: normal
  mean: 196.8
  sd: 44.8

quality:
  mean_quality: 32
  tail_decay: 0.0011

tumour:
  purity: 0.003882
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0020_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 2.20
  family_size_sd: 0.79

chromosomes:
  - chr1

seed: 446753
