# varforge config: SV_ML3_TRAIN_VAF0279_0379 — VAF 3.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0279_0379
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0279_0379
  read_length: 150
  coverage: 767.1
  platform: illumina

fragment:
  model: normal
  mean: 201.1
  sd: 15.1

quality:
  mean_quality: 38
  tail_decay: 0.0024

tumour:
  purity: 0.055824
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0300_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.51
  family_size_sd: 2.01

chromosomes:
  - chr1

seed: 448267
