# varforge config: SV_ML3_TRAIN_VAF1140_0847 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf1140_0847
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF1140_0847
  read_length: 150
  coverage: 4747.8
  platform: illumina

fragment:
  model: normal
  mean: 248.4
  sd: 27.1

quality:
  mean_quality: 38
  tail_decay: 0.0016

tumour:
  purity: 0.228073
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 5.59
  family_size_sd: 2.90

chromosomes:
  - chr1

seed: 497342
