# varforge config: SV_ML3_TRAIN_VAF0182_0771 — VAF 1.7500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0182_0771
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0182_0771
  read_length: 150
  coverage: 559.8
  platform: illumina

fragment:
  model: normal
  mean: 167.3
  sd: 26.5

quality:
  mean_quality: 35
  tail_decay: 0.0018

tumour:
  purity: 0.036336
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0175_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 8
  family_size_mean: 2.41
  family_size_sd: 1.28

chromosomes:
  - chr1

seed: 461587
