# varforge config: SV_ML3_TRAIN_VAF0029_1820 — VAF 0.3000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0029_1820
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0029_1820
  read_length: 150
  coverage: 13753.2
  platform: illumina

fragment:
  model: normal
  mean: 237.4
  sd: 45.7

quality:
  mean_quality: 34
  tail_decay: 0.0029

tumour:
  purity: 0.005725
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0030_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 10
  family_size_mean: 6.24
  family_size_sd: 3.02

chromosomes:
  - chr1

seed: 405581
