# varforge config: SV_ML3_TRAIN_VAF0006_1420 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0006_1420
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0006_1420
  read_length: 150
  coverage: 9898.3
  platform: illumina

fragment:
  model: normal
  mean: 221.3
  sd: 31.3

quality:
  mean_quality: 32
  tail_decay: 0.0049

tumour:
  purity: 0.001186
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 8.30
  family_size_sd: 1.97

chromosomes:
  - chr1

seed: 461384
