# varforge config: SV_ML3_TRAIN_VAF0910_0610 — VAF 10.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0910_0610
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0910_0610
  read_length: 150
  coverage: 8821.1
  platform: illumina

fragment:
  model: normal
  mean: 277.6
  sd: 21.0

quality:
  mean_quality: 33
  tail_decay: 0.0046

tumour:
  purity: 0.182056
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf1000_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 2.53
  family_size_sd: 1.02

chromosomes:
  - chr1

seed: 455626
