# varforge config: SV_ML3_TRAIN_VAF0145_0529 — VAF 1.5000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0145_0529
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0145_0529
  read_length: 150
  coverage: 7556.0
  platform: illumina

fragment:
  model: normal
  mean: 151.7
  sd: 22.6

quality:
  mean_quality: 36
  tail_decay: 0.0016

tumour:
  purity: 0.029088
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0150_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 6
  family_size_mean: 9.03
  family_size_sd: 1.94

chromosomes:
  - chr1

seed: 426228
