# varforge config: SV_ML3_TRAIN_VAF0389_1705 — VAF 4.0000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0389_1705
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0389_1705
  read_length: 150
  coverage: 7533.0
  platform: illumina

fragment:
  model: normal
  mean: 233.6
  sd: 39.0

quality:
  mean_quality: 34
  tail_decay: 0.0035

tumour:
  purity: 0.077880
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0400_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 4
  family_size_mean: 4.38
  family_size_sd: 1.43

chromosomes:
  - chr1

seed: 425040
