# varforge config: SV_ML3_TRAIN_VAF0003_0783 — VAF 0.0500%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0003_0783
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0003_0783
  read_length: 150
  coverage: 4134.4
  platform: illumina

fragment:
  model: normal
  mean: 214.6
  sd: 39.0

quality:
  mean_quality: 39
  tail_decay: 0.0018

tumour:
  purity: 0.000652
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0005_b.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 9
  family_size_mean: 4.17
  family_size_sd: 1.63

chromosomes:
  - chr1

seed: 402948
