# varforge config: SV_ML3_TRAIN_VAF0010_1602 — VAF 0.1000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0010_1602
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0010_1602
  read_length: 150
  coverage: 19896.1
  platform: illumina

fragment:
  model: normal
  mean: 134.8
  sd: 29.4

quality:
  mean_quality: 36
  tail_decay: 0.0013

tumour:
  purity: 0.002094
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0010_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 13
  family_size_mean: 3.79
  family_size_sd: 1.41

chromosomes:
  - chr1

seed: 424135
