# varforge config: SV_ML3_TRAIN_VAF0045_1418 — VAF 0.4000%
reference: docs/benchmarking/sv/data/ref.fa

output:
  directory: docs/benchmarking/ml/results/train/sim_sv_ml3_train_vaf0045_1418
  fastq: true
  bam: false
  truth_vcf: true
  manifest: true

sample:
  name: SV_ML3_TRAIN_VAF0045_1418
  read_length: 150
  coverage: 1683.0
  platform: illumina

fragment:
  model: normal
  mean: 199.4
  sd: 25.5

quality:
  mean_quality: 30
  tail_decay: 0.0021

tumour:
  purity: 0.008986
  ploidy: 2

mutations:
  vcf: docs/benchmarking/sv/data/truth_svs_vaf0040_a.vcf

umi:
  length: 5
  duplex: true
  pcr_cycles: 12
  family_size_mean: 2.03
  family_size_sd: 1.12

chromosomes:
  - chr1

seed: 456857
